### ISSUE TITLE
Feature Request : need serializer, deserializer for Option<Datetime>

### ISSUE THREAD

**Issue by ktjd123** [mongodb/mongo-rust-driver#1032]
## Versions/Environment
1. What version of Rust are you using? 1.76.0
2. What operating system are you using? macOs 14.3.1
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
registry+https://github.com/rust-lang/crates.io-index#mongodb@2.8.1
registry+https://github.com/rust-lang/crates.io-index#bson@2.9.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`)  7.0.2
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? standalone

## Describe the bug

The `mongodb::bson::serde_helpers::chrono_datetime_as_bson_datetime` doesn't support Option<Datetime>.

**Comment by abr-egn** [comment]
Unfortunately, it's not feasible for us to provide helper functions for all the various permutations of conversions here.  You should be able to write your own - if you look at the [source](https://github.com/mongodb/bson-rust/blob/main/src/serde_helpers.rs#L283) for `chrono_datetime_as_bson_datetime` a helper for `Option<Datetime>` would be very similar.
