### ISSUE TITLE
The solution for balancing the load of read operations.

### ISSUE THREAD

**Issue by westYY123** [mongodb/mongo-rust-driver#1068]
suppose i have a mongodb cluster within 1 primary and 2 secondary using replica set mode, I would like to make the reading operations be assigned to a node(whatever it is primary or secondary) randomly, is there any method to approach this problem?

**Comment by abr-egn** [comment]
Directing read operations to particular nodes is done by configuring the [Read Preference](https://www.mongodb.com/docs/manual/core/read-preference/); in the Rust driver, the default read preference for a client can be set in the [connection string](https://www.mongodb.com/docs/manual/reference/connection-string/#read-preference-options) or it can be set for a particular scope (database, collection, or individual operation) by setting the appropriate [`selection_criteria`](https://docs.rs/mongodb/latest/mongodb/options/enum.ReadPreference.html?search=selection_criteria) option.
