### ISSUE TITLE
Infinite loop while parsing results from find({}, None)

### ISSUE THREAD

**Issue by topongo** [mongodb/mongo-rust-driver#1069]
## Versions/Environment
1. What version of Rust are you using?
1.79.0-nightly
2. What operating system are you using?
arch linux
3. What versions of the driver and its dependencies are you using? (Run `cargo pkgid mongodb` & `cargo pkgid bson`)
mongodb: 2.8.2
bson: 2.9.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
7.0.5
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
standalone (docker)

## Describe the bug
While parsing documents from a collection using the following code snippet
```rust
while let Some(s) = db.collection("stops").find(doc!{}, None).await?.try_next().await? {
    // do something
}
```
The end of iterator value `None` is never returned by try_next(), and so a infinite loop is generated.

### Things I tried
- using a different filter (eg. `doc!{"id": 15}`) but the behavior doesn't change
- using `next()` instead of `try_next()`

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
I'm expecting `.next()` to return a `None` at some point thus breaking the while loop
* Do you have any particular output that demonstrates this problem?
No output, the code hangs.
* Do you have any ideas on _why_ this may be happening that could give us a clue in the right direction?
I've no clue, what I'm sure of is that, giving the fact that collecting into a vec works it may be a problem of the `next`/`try_next` methods.
* Did this issue arise out of nowhere, or after an update (of the driver, server, and/or Rust)? 
I always used to collect into `Vec`s, today I tried this method, that I think is less reduntant and it happend.
* Are there multiple ways of triggering this bug (perhaps more than one function produce a crash)?
afaik no

## How to reproduce
`Cargo.toml`:
```rust
[package]
name = "infinite_loop_mongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "^0.3"
mongodb = "^2.8"
tokio = "^1.37"
```

`main.rs`:
```rust
use mongodb::{options::{ClientOptions, Credential}, Client};
use mongodb::bson::doc;
use futures::stream::StreamExt;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db = Client::with_options(ClientOptions::builder()
        .credential(Credential::builder()
            .username("redacted".to_owned())
            .password("redacted".to_owned())
            .build())
        .build()).unwrap().database("bruss");

    while let Some(_) = db.collection::<()>("stops")
        .find(doc!{}, None)
        .await?
        .next()
        .await
    {
        // do something
        println!("loop");
    }

    Ok(())
}
```

**Comment by abr-egn** [comment]
I think the issue is that you're re-executing the `find` with each iteration of the loop, so you're only ever getting the first item that matches.  Something like this should work:
```rust
    let mut cursor = db.collection::<()>("stops").find(doc!{}, None).await?;
    while let Some(_) = cursor.next().await {
        // do something
        println!("loop");
    }
```

**Comment by topongo** [comment]
oh well, that's embarassing, thank you. probably i should've seen that coming
