### ISSUE TITLE
RUST-1913 Compilation error when handling ErrorKind::GridFs

### ISSUE THREAD

**Issue by rigens** [mongodb/mongo-rust-driver#1071]
## Versions/Environment
1. What version of Rust are you using?  
    _rustc 1.77.2 (25ef9e3d8 2024-04-09)_
2. What operating system are you using?
    _Ubuntu 20.04_
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
    _mongodb@2.8.2_
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
   _4.2.2_
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
    _standalone_

## Describe the bug
I get a compilation error when handling ErrorKind::GridFs error

```rust
    let client = Client::with_uri_str("mongodb://localhost:27017/test").await.unwrap();
    let db = client.default_database().unwrap();
    let bucket = db.gridfs_bucket(None);
    
    let res = bucket.delete(Bson::String("1234567".to_string())).await;
    
    match res {
        Ok(_) => {println!("ok")}
        Err(err) => {
            match *err.kind {
                ErrorKind::GridFs(_) => {println!("gridfs error")}
                _ => {println!("other mongodb error")}
            }
        }
    }
```

```
    |
130 |                 ErrorKind::GridFs(_) => {println!("gridfs error")}
    |                            ^^^^^^ private tuple variant
    |
    |
573 |     #[non_exhaustive]
    |     ----------------- cannot be constructed because it is `#[non_exhaustive]`
574 |     GridFs(GridFsErrorKind),
    |     ^^^^^^
```

**Comment by abr-egn** [comment]
Thanks for the bug report!  I've just merged https://github.com/mongodb/mongo-rust-driver/pull/1079 to fix this.
