### ISSUE TITLE
Find one options, projection method not working for inclusions.

### ISSUE THREAD

**Issue by iosamoritz** [mongodb/mongo-rust-driver#1075]
Hallo, 
I am working with the Rust driver for Mongodb, (lastest version both). 
When trying to create a projection, to select one mongodb field to be retrieved (inclusion), after calling the find_one() method, does not work as it should be. It cannot find document.
In other words, the equivalent of the following in mongosh:
db.<collection_name>.findOne({<filter>: "value"},{"wanted_field": 1})
Does not work with the Rust driver.
Anyone else has noticed this ?

**Comment by abr-egn** [comment]
Can you give an example of:
* the Rust code you're using for the find
* data that's present in your db
* what you expect the query to return, and what it actually returns

**Comment by iosamoritz** [comment]
I do not understand why you ask.
Are you suggesting already that it works.

struct User {
   Id: Option<ObjectId>,
   email: String,
   label: String,
   age: i32,
}
let filter = doc! {"email": "myemail@test.io"}
let options = findOne options::builder().projection("label":1).build();
let res = 
   collection.find_one(filter, options).await.ok().expect("Document not found");

This should retrieve the label field for the user filtered, any test I have done , different fields, dbs, collections, did not work.
Prints the .expect msg. (Document not found)

Equivalent in mongosh:

db.user.findOne({"email":"myemail@test.io"},{"label":1})
This prints the label and the _id fields.

(Sorry I am not very familiar with the GitHub notations and son on,)

**Comment by abr-egn** [comment]
I think I see the issue.  `Collection` has a type parameter and will automatically deserialize documents as that type; I'm guessing that the type of your `collection` variable is `Collection<User>`.  When you use a projection to only return the `label` field, that makes the resulting documents no longer able to be deserialized as `User` structs.  The `Error` returned from `find_one` will indicate this:
```
thread 'test::project::test_project' panicked at src/test/project.rs:34:10:
find failed: Error { kind: BsonDeserialization(DeserializationError { message: "missing field `email`" }), labels: {}, wire_version: None, source: None }
```
Your code is discarding that error with the `ok()` call, so you're only seeing the `expect` message.  To look up documents that don't match the type parameter, you can use the [`clone_with_type`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.clone_with_type) method before calling `find_one`.  Here's an example test using all of this that passes:
```rust
#[tokio::test]
async fn test_project() {
    #[derive(Serialize, Deserialize)]
    struct User {
        email: String,
        label: String,
    }

    let client = Client::test_builder().build().await;
    let collection = client.database("test").collection::<User>("test_project");
    collection.drop(None).await.unwrap();
    collection
        .insert_one(
            User {
                email: "myemail@test.io".to_string(),
                label: "test label".to_string(),
            },
            None,
        )
        .await
        .unwrap();

    let filter = doc! {"email": "myemail@test.io"};
    let options = FindOneOptions::builder()
        .projection(doc! {"label":1})
        .build();
    let res = collection
        .clone_with_type::<Document>()
        .find_one(filter, options)
        .await
        .expect("find failed")
        .expect("Document not found");

    assert_eq!(res.get_str("label").unwrap(), "test label");
}
```

**Comment by abr-egn** [comment]
> Hey, Thanks very much for your answer. It would have been nice to see this in the documentation.

Very true!  I was surprised to see we didn't mention it in the documentation for `project`.  I've filed RUST-1912 to address that.

> So if you are right, what exactly is happening in exclusions, I noticed that when using only excluding fields it returns a deserialized User excluding the field in question. Would you agree if I say that it contradicts your explanation.

If the fields in the `User` struct are `Option<T>`, deserialization won't require them in the document.  Is that the case for the fields you're excluding?

**Comment by iosamoritz** [comment]
Yes, that is actually correct, my mistake, I initially interpreted this as inconsistency untill I just realized now after further exploration that in all cases the fields I was testing are all Option<T> (Vector, bool, so on ..).
Sorry, I pointing at performance, so my mongodb instance is 99% embedded docs, I have many many fields.
Thanks for adding the relevant amendment to the projection feature.
