### ISSUE TITLE
Connecting to MongDB Atlas seems to take ~40s every time

### ISSUE THREAD

**Issue by Jasper-Bekkers** [mongodb/mongo-rust-driver#1112]
## Versions/Environment
1. What version of Rust are you using? **1.78**
3. What operating system are you using? **Windows**
4. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) **2.8.2**, problem persists on main branch
5. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 7.3.2
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? serverless

## Describe the bug
When using this crate with `mongodb+srv://` makes the `ClientOptions::parse` function take ~40s. Additionally, when connecting with `mongodb://` it connects nearly instantly, but then fails with the following error messages (unclear if related).

```
called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: evolve-highscores.4ngync0.mongodb.net:27017, Type: Unknown, Error: Kind: I/O error: No such host is known. (os error 11001), labels: {} } ] }" }, labels: {}, wire_version: None, source: None }
```

When connecting through MongoDB Compass it connects near instantly, when connecting through nodejs it connects near instantly.

```rust
...

#[tokio::main]
async fn main() {
    use mongodb::{
        options::{ClientOptions, FindOptions},
        Client,
    };
    let k = std::time::Instant::now();
    println!("start: {:?}", k.elapsed());

    let mut client_options = ClientOptions::parse("mongodb+srv://..mongodb.net....")
    .await
    .unwrap();

    println!("ClientOptions: {:?}", k.elapsed());
}
```

Digging in with the profiler it's showing something interesting:
Tokio seems to be mostly doing nothing for ~5 seconds in between bursts in which it's trying to do some DNS related activity for ~1ms

Data captured with Superluminal Profiler, red indicates "thread is stalling" and specifically in this case it's in SwapContext (win32)
![image](https://github.com/mongodb/mongo-rust-driver/assets/49594/835e56a7-3717-4f87-a516-0b7a5b927e54)

If we zoom in a bit more we can see there are distinc sections of "nothing" for 5 seconds:

![image](https://github.com/mongodb/mongo-rust-driver/assets/49594/6e01d388-4465-40d8-8cf0-e1e4de45dcfc)

If we zoom in to what's going on inbetween these 5 seconds it becomes a bit clear:

![image](https://github.com/mongodb/mongo-rust-driver/assets/49594/5a029217-bab1-4dae-95fd-0c69518b3f4d)

Here we see that we end up in small calls to `trust_dns`. Right now for me it's unclear if this is a problem with trust-dns or if this is related to something this crate is doing. However the fact that nodejs and Compass don't have this behavior definitely seems to indicate that something is going wrong on the Rust side of things.

**Comment by Jasper-Bekkers** [comment]
Alright looks like the default timeout on trust-dns is 5 seconds and it'll try a bunch of things sequentially.

Changing `AsyncResolver` as follows and passing in a custom `ResolverConfig` speeds things up significantly.

```
    pub(crate) async fn new(config: Option<ResolverConfig>) -> Result<Self> {
        let resolver = match config {
            Some(config) => {
                let mut opts = trust_dns_resolver::config::ResolverOpts::default();
                opts.timeout = std::time::Duration::from_millis(100); // the change
                trust_dns_resolver::TokioAsyncResolver::tokio(config, opts).map_err(Error::from_resolve_error)?
            }
            None => trust_dns_resolver::TokioAsyncResolver::tokio_from_system_conf() // need to bypass this since it's using default values
                .map_err(Error::from_resolve_error)?,
        };

        Ok(Self { resolver })
    }
}
```

**Comment by abr-egn** [comment]
Yup, this is unfortunately a known issue in `trust-dns-resolver` that we can't do much about :(  https://crates.io/crates/mongodb#windows-dns-note

**Comment by Jasper-Bekkers** [comment]
> Yup, this is unfortunately a known issue in `trust-dns-resolver` that we can't do much about :(  https://crates.io/crates/mongodb#windows-dns-note

Thanks for linking the readme, I couldn't an actual issue for this when looking so it appears its mostly untracked on the mongodb side.

Can we work with the trust-dns community to fix this? It seems like it would hamper prototyping and development quite a bit?
