### ISSUE TITLE
centos7 try_next is error

### ISSUE THREAD

**Issue by zqlpaopao** [mongodb/mongo-rust-driver#1114]
```
   let mut cursor = coll
        .find(
            doc! {
            "idc_id":idc,
            "module":module
            },
            find_options,
        )
        .await?;
    println!("{:?}",cursor);
     match cursor.next().await{
        None => {}
        Some(res) => {
            println!("{:?}",res);


        }
    };
```

This code cannot obtain a value during Linux Centos7 compilation, but it is possible in Mac m1

**Comment by isabelatkinson** [comment]
Hi @zqlpaopao, can you provide more details about the results you're receiving on each platform? Are you encountering an error on Linux, or does the call to `find` return an empty cursor?
