### ISSUE TITLE
Can I efficiently `.skip()` and `.limit()` a `Cursor<T>`?

### ISSUE THREAD

**Issue by clarkmcc** [mongodb/mongo-rust-driver#1145]
Is this

```rust
cursor
        .limit(10)
        .skip(20)
        .try_collect()
        .await;
```

equivalent to tacking this on the end of an aggregate query?
```json
[
    ...
    {
        "$skip": 20
    },
    {
        "$limit": 10
    },
]
```

The reason I ask is I was thinking these are Rust standard iterator methods, and if so, I was thinking that still would read the 20 skipped records out of the database, and just not start yielding values until 21.

**Comment by abr-egn** [comment]
Once the `Cursor` has been constructed, using methods like `skip` will indeed unfortunately iterate over the underlying records.  Note that the records are fetched in batches from the server, so the performance implications of that will vary quite a bit depending on configured batch size; if the skip doesn't hit a batch boundary it would just be incrementing an in-memory counter.

**Comment by clarkmcc** [comment]
Makes sense. Theoretically these methods could be implemented for `Aggregate` though right, since that exists before the cursor is constructed? Something like this

```rust
let aggregate: Aggregate<()> = client
        .database("db")
        .collection("col")
        .aggregate(vec![])
        .with_type::<()>();
    
// Another function somewhere else
let cursor = aggregate.skip(20).limit(10).await?;
```

I believe the NodeJS client allows you to have this sort of developer experience decoupling the pagination from the actual query.

**Comment by abr-egn** [comment]
Interesting, it looks like the way the NodeJS driver does this is it has a single [`AggregationCursor`](https://mongodb.github.io/node-mongodb-native/6.7/classes/AggregationCursor.html) type that both allows modifying the pipeline and iterating, and it has runtime checks for the pipeline modifications that no iteration has happened yet.

It would definitely be possible to add similar pipeline convenience methods to the Rust driver's `Aggregate` action type; feel free to file a feature request (or send a PR 🙂).

**Comment by clarkmcc** [comment]
I'd be happy to work on a PR. Does the implementation need to be any more special than this?

```diff
Index: src/action/aggregate.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/action/aggregate.rs b/src/action/aggregate.rs
--- a/src/action/aggregate.rs	(revision 08e2923eda642596ab06f18fd99da0f12c97690e)
+++ b/src/action/aggregate.rs	(date 1719255641437)
@@ -1,6 +1,6 @@
 use std::{marker::PhantomData, time::Duration};
 
-use bson::Document;
+use bson::{doc, Document};
 
 use crate::{
     coll::options::AggregateOptions,
@@ -176,6 +176,23 @@
             _phantom: PhantomData,
         }
     }
+
+    pub fn skip(mut self, n: i64) -> Self {
+        self.push_stage(doc! { "$skip": n })
+    }
+
+    pub fn limit(mut self, n: i64) -> Self {
+        self.push_stage(doc! { "$limit": n })
+    }
+
+    pub fn sort(mut self, doc: Document) -> Self {
+        self.push_stage(doc! { "$sort": doc })
+    }
+
+    fn push_stage(mut self, doc: Document) -> Self {
+        self.pipeline.push(doc);
+        self
+    }
 }
 
 #[action_impl(sync = crate::sync::Cursor<T>)]

```

**Comment by abr-egn** [comment]
Nope, I think that's about all that's needed :)
