### ISSUE TITLE
What happened to `bson-chrono-0_4` flag?

### ISSUE THREAD

**Issue by kukuro-kt** [mongodb/mongo-rust-driver#1152]
I cannot find any description from [migration-3.0.md](https://github.com/mongodb/mongo-rust-driver/blob/main/migration-3.0.md)
It just disappeared?
What is the recommended way now?

**Comment by abr-egn** [comment]
Sorry, we missed this in the migration guide!  I'll be sure to add a section.

The various `bson-*` features were removed because there wasn't actually a need for them - to enable features in `bson`, you can include it as a dependency directly in your project.
