### ISSUE TITLE
How to enable the `chrono-0_4` feature of `bson` which comes with `mongodb` crate?

### ISSUE THREAD

**Issue by mominul** [mongodb/mongo-rust-driver#1163]
In mongodb crate version 2.8.0, there was a feature flag `bson-chrono-0_4` which could enable the  `chrono-0_4` feature of `bson` crate which comes bundled.

```
mongodb = { version = "3", features = ["bson-chrono-0_4"] }
```

But in the `3.0.0` version, the feature flag doesn't exist, and cargo reports the following error if I try to use the `bson-chrono-0_4` feature flag:
```
depends on `mongodb`, with features: `bson-chrono-0_4` but `mongodb` does not have these features.
```

So what is the way out here, should we depend on `bson` directly with `chrono-0_4` feature flag enabled?

Thanks in advance 😄

**Comment by abr-egn** [comment]
Yup, as we mentioned in the [migration guide](https://github.com/mongodb/mongo-rust-driver/blob/main/migration-3.0.md#bson--features-removed) directly depending on `bson` with the features you need is the way to go.
