### ISSUE TITLE
Better way to populate a field in mongodb rust

### ISSUE THREAD

**Issue by ChanManChan** [mongodb/mongo-rust-driver#1194]
I know we can populate a field using aggregate functions "$lookup" feature but is there a better and easy way to just populate a single field like in mongoose library for nodejs?

**Comment by isabelatkinson** [comment]
Hi @ChanManChan, the driver does not have any equivalent API to the populate functionality in mongoose; you'll need to call the [`aggregate`](https://docs.rs/mongodb/latest/mongodb/struct.Database.html#method.aggregate) method with a `$lookup` stage to do something similar in the driver.

**Comment by ChanManChan** [comment]
Thanks for the help.
