### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: JoinError::Cancelled(Id(32))

### ISSUE THREAD

**Issue by Glydric** [mongodb/mongo-rust-driver#1204]
## Versions/Environment
1. What version of Rust are you using?  1.81.0
2. What operating system are you using? MacOS 14.6
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
registry+https://github.com/rust-lang/crates.io-index#mongodb@3.1.0
registry+https://github.com/rust-lang/crates.io-index#bson@2.11.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 7.0.12
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? replica set

## Describe the bug
When running actix tests (api that connects with mondogb) sometimes I get 
```called `Result::unwrap()` on an `Err` value: JoinError::Cancelled(Id(32)) ``` 
this happens on file mongodb-3.1.0/src/runtime/join_handle.rs:32:60

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening? 
* Do you have any particular output that demonstrates this problem?
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
* If you know how to reproduce this bug, please include a code snippet here:
```

```

**To Reproduce**
1. First, do this.
2. Then do this.
3. After doing that, do this.
4. And then, finally, do this.
5. Bug occurs.

**Comment by abr-egn** [comment]
Can you provide more information about the test setup that's triggering this error?  The error location you list is generic functionality.

Since the error is 'JoinError::Cancelled` (which I believe comes from Tokio when a task is explicitly cancelled), note that the Rust mongodb driver is [not cancel-safe](https://docs.rs/mongodb/latest/mongodb/#warning-about-timeouts--cancellation).
