### ISSUE TITLE
Change Stream Support

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [mongodb/mongo-rust-driver#1230]
It is documented that change streams can be specifically targeted e.g. https://www.mongodb.com/docs/manual/changeStreams/?msockid=02a68eedad1c61261ab59beeac1a6098#modify-change-stream-output.

This functionality however does not appear to be currently available in this library.

In a large database with many updates I am assuming this is very important for performance.

What is the status of support here?

**Comment by isabelatkinson** [comment]
Hi @JonathanWoollett-Light, is the [`pipeline`](https://docs.rs/mongodb/latest/mongodb/action/struct.Watch.html#method.pipeline) method the functionality you're looking for here? e.g.

```
let change_stream = coll
    .watch()
    .pipeline(pipeline)
    .await?;
```
