### ISSUE TITLE
replace or remove derivative -- it is unmaintained

### ISSUE THREAD

**Issue by ctriley** [mongodb/mongo-rust-driver#1252]
## Versions/Environment
What version of Rust are you using? 
1.82.0

What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
registry+https://github.com/rust-lang/crates.io-index#bson@2.13.0
registry+https://github.com/rust-lang/crates.io-index#mongodb@3.1.0

## Describe the bug
error[unmaintained]: `derivative` is unmaintained; consider using an alternative
   ┌─ /home/runner/work/ontra/ontra/dispatching/Cargo.lock:56:1
   │
56 │ derivative 2.2.0 registry+https://github.com/rust-lang/crates.io-index
   │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
   │
advisories FAILED
   ├ ID: RUSTSEC-2024-03[8](https://github.com/mobility-solutions-inc/ontra/actions/runs/11827322647/job/33474504993#step:5:9)8
   ├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
   ├ The [`derivative`](https://crates.io/crates/derivative) crate is no longer maintained.
     Consider using any alternative, for instance:
     - [derive_more](https://crates.io/crates/derive_more)
     - [derive-where](https://crates.io/crates/derive-where)
     - [educe](https://crates.io/crates/educe)
   ├ Announcement: https://github.com/mcarton/rust-derivative/issues/117

**Comment by isabelatkinson** [comment]
Hey @ctriley, `derivative` was removed in #1245 which will be included in the next release.
