### ISSUE TITLE
thread 'main' panicked at 'there is no timer running

### ISSUE THREAD

**Issue by govo** [mongodb/mongo-rust-driver#384]
Using mongodb = 1.2.2
the example code from doc:
```
// get error
let options = ClientOptions::builder()
    .hosts(vec![StreamAddress {
      hostname: "localhost".into(),
      port: Some(27017),
    }])
    .build();
  let client = Client::with_options(options)?;
  let db = client.database("some_db");
  for coll_name in db.list_collection_names(None).await.unwrap() {
    println!("collection: {}", coll_name);
  }
```
got the error:

thread 'main' panicked at 'there is no timer running, must be called from the context of a Tokio 0.2.x runtime', /Users/xxx/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.2.25/src/time/driver/handle.rs:24:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

using mongodb = 0.9.2 is ok:
```
// works
  let client = Client::with_uri_str("mongodb://localhost:27017/").unwrap();
  let options = ClientOptions::builder()
    .hosts(vec![StreamAddress {
      hostname: "localhost".into(),
      port: Some(27017),
    }])
    .build();
  let client = Client::with_options(options)?;
  let db = client.database("main");
  for coll_name in db.list_collection_names(None).unwrap() {
    println!("collection: {}", coll_name);
  }
```

all With tokio = { version = "1.7.1", features = ["full","test-util"] }

**Comment by govo** [comment]
I finally try out:
using this in Cargo.toml will fix it.
```
[dependencies.mongodb]
version = "1.2.2"
default-features = false
features = ["async-std-runtime"]
```

**Comment by AsianIntel** [comment]
mongodb 1.2 has tokio 0.2 as a dependency, whereas you're using tokio 1.7, which is why you're getting this error. If you want to use tokio `1.x`, you need to put mongodb's version as `2.0.0-beta.2` (This is the latest one) and enable the `tokio-runtime` feature (it's enabled by default).

**Comment by Kiiyya** [comment]
Any roadmap or ballpark figure when v2.0 will drop?
