### ISSUE TITLE
Change streams support

### ISSUE THREAD

**Issue by xamgore** [mongodb/mongo-rust-driver#418]
Hi! Thank you, folks, for implementing the MongoDB driver for Rust. Though I'm concerned, is it really possible to use change streams. If not, when do you plan to implement this feature?

**Comment by lamafab** [comment]
Yes, I'd really appreciate to have change streams supported.

Previous issue on change streams (deprecated repo): https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/246
Looks like there was a work-in-progress PR that was never merged: https://github.com/mongodb-labs/mongo-rust-driver-prototype/pull/302

**Comment by abr-egn** [comment]
Unfortunately, the Rust driver doesn't currently have support for change streams.

Happily, this is in our plan to implement for this quarter; currently we expect it to land in October.  You can follow RUST-519 to track progress on the work.

**Comment by xamgore** [comment]
As I may see, [RUST-521](https://jira.mongodb.org/browse/RUST-521) is on track now.
