### ISSUE TITLE
Documentation request: The <T> in Collection<T> stands for Document

### ISSUE THREAD

**Issue by slyons** [mongodb/mongo-rust-driver#425]
In the v2 of the driver there's a shift to using `Collection<T>`, but you have to dig into the tests to discover just what the `<T>` is supposed to be. A Doctest or something in the documentation would be appreciated.

**Comment by abr-egn** [comment]
Hi!

We certainly need to update our documentation prior to the full 2.0 release - we have a ticket for that [here](https://jira.mongodb.org/browse/RUST-736), and we'll make sure that includes information and examples on what types can be used with `Collection`.  As a quick preview, the driver uses `serde` to support user-defined types, so any type that implements `DeserializeOwned` will work for read operations, and any type that implements `Serialize` will work for write operations :)
