### ISSUE TITLE
Hi! Is there a working mini example for Actix current version? 

### ISSUE THREAD

**Issue by bitdom8** [mongodb/mongo-rust-driver#426]
Have tried many times but no can do

**Comment by isabelatkinson** [comment]
Hi @bitdom8! We currently have work in flight to create examples and documentation for using the Rust driver with web frameworks. RUST-745 tracks the Actix portion of this work, so feel free to follow that ticket for updates on when these examples will be published!

**Comment by bitdom8** [comment]
Thx this is great. Been looking for this

**Comment by dallinwright** [comment]
@bitdom8 I can help you out maybe, I have a working microservice with the mongodb create 1.2.2 and the latest actix_web verison.

This is my main function:

```
#[actix_web::main(flavor = "multi_thread", worker_threads = 10)]
async fn main() -> tokio::io::Result<()> {
    dotenv().ok();
    let mongodb_uri: String = env::var("MONGODB_URI").expect("MONGODB_URI env var not set!");
    let mut client_options: ClientOptions = ClientOptions::parse_with_resolver_config(mongodb_uri.as_str(), ResolverConfig::cloudflare()).await.unwrap();
    client_options.app_name = Some("my_app".to_string());
    let client: mongodb::Client = mongodb::Client::with_options(client_options).expect("Could not create utils.mongodb client");
    // Get a handle to a database.
    let db: Database = client.database("shared");
    log::info!("Server established MongoDB connection pool");

    let bind_addr = "127.0.0.1:8080";
    println!("Server running at {} ....", bind_addr);

    SimpleLogger::new().env().init().unwrap();
    log::info!("Server started ENV: {}", CONFIG.env);

    let app_state: AppState = AppState {
        database: Arc::new(db.clone())
    };

    HttpServer::new(move || {
        App::new()
            .data(app_state.clone())
            .wrap(middleware::Compress::default())
            .service(index)
    })
        .bind(bind_addr)?
        .run()
        .await
}
```

That will get you sorted with the passing in the mongodb connection pool. For the app state, it's just this struck in the fame file `main.rs`

```
#[derive(Clone, Debug)]
struct AppState {
    database: Arc<Database>,
}
```

Then in your route, you have something like this, and you can access the DB and call it!

```
#[post("/")]
async fn index(
    data: web::Data<AppState>,
    request: web::Json<IncomingRequest>,
) -> Result<HttpResponse, ApiError> {
    log::info!("Incoming request: {:#?}", request);
    let database: Arc<Database> = data.database.clone();
```

You pass the Arc down to where you need it, it is a thread safe container basically for the mongodb connection. You can pass/do whatever in child functions with it.

**Comment by bitdom8** [comment]
Thanks @dallinwright , this seems great. Have applied mongodb and golang. However i will benefit this useful codes for some pages with rust backend. Also if you have stacks exchange profile, will follow you

**Comment by isabelatkinson** [comment]
Hi @bitdom8, the [MongoDB/Actix example](https://github.com/actix/examples/pull/452) has been merged. I'm going to close out this issue, but feel free to file another one if you have further questions!
