### ISSUE TITLE
How to do bulkWrite

### ISSUE THREAD

**Issue by prantor19** [mongodb/mongo-rust-driver#434]
Is there any way to perform bulk write

https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/

**Comment by linde12** [comment]
Hey @patrickfreed - sorry to reach out like this, but do you have any idea if will be implemented? I know there is a JIRA for it, but i remember seeing some information saying that it would _not_ be implemented at all.

Thanks, great work so far!
