### ISSUE TITLE
Sync reads and async writes

### ISSUE THREAD

**Issue by MartinSkovsen** [mongodb/mongo-rust-driver#453]
Thank you for providing a rust driver for mongodb!

Since the async API is privatized when you import the sync feature, how would I go about making async writes? I'd really lik to make sync reads, but since the async API is limited, what would I do in my scenario?

Thank you so much in advance :)

**Comment by abr-egn** [comment]
Hi!

In this scenario, you should use the async API - you can wrap the reads with a call to the runtime to block on the result, which will translate it to a sync call (this is actually how the sync API is implemented under the hood).
