### ISSUE TITLE
Support for mongodb+consul?

### ISSUE THREAD

**Issue by mycraftmw** [mongodb/mongo-rust-driver#455]
Hi there, I'd like to know if this driver supports `mongodb+consul` scheme now? If not, do we have a plan for it?

**Comment by mycraftmw** [comment]
Oops, seem like the current version doesn't support `mongodb+consul` yet. :(

```
'cannot connect to mongodb: Error { kind: InvalidArgument { message: "invalid connection string scheme: mongodb+consul" }, labels: {} }'
```

So do we have a plan for it?

**Comment by kmahar** [comment]
Hello @mycraftmw, thank you for reaching out.

As far as I'm aware supporting connection strings of the form `mongodb+consul...` is not something any drivers support, or plan to. However, what I think you may be referring to is the work described by [DRIVERS-521](https://jira.mongodb.org/browse/DRIVERS-521), to allow custom service names (including Consul) to be specified in connection strings?

We are still in discussions on what exactly that support should look like in connection strings, as you can see on mongodb/specifications#1067.  Once the specification work in that pull request is completed and merged in and we know what changes we need to make, we will then be able to implement support for this in drivers including Rust. The relevant ticket to track would be RUST-911. 

Let me know if that's what you were looking for and if you have any further questions.
