### ISSUE TITLE
Use Arc::clone in Collection::clone_with_type

### ISSUE THREAD

**Issue by PhotonQuantum** [mongodb/mongo-rust-driver#464]
Current `clone_with_type` implementation includes calling builder and constructing a new `CollectionInner` instance.
Given that `CollectionInner` is wrapped in an Arc, and generic T isn't included in `CollectionInner`, is there any possibility that we refactor `clone_with_type` into `Self{inner: self.inner.clone(), _phantom: Default::default()}`?

**Comment by patrickfreed** [comment]
Hi @PhontonQuantum, thanks for bringing this up! We think that would be a nice improvement and would be happy to merge such a change if you'd like to submit a PR for it.
