### ISSUE TITLE
Is there a bulk write operation for the official driver?

### ISSUE THREAD

**Issue by iammeosjin** [mongodb/mongo-rust-driver#468]
I have a vec of doc and wanted to apply an update operation in bulk but i couldn't find any documentation or example.

**Comment by agolin95** [comment]
Hi @iammeosjin, we don't currently have a Bulk Write implementation in the driver but we have had regular discussions about pursuing this in the future. In the meantime, please feel free to watch this existing issue to keep track of this: https://jira.mongodb.org/browse/RUST-531

**Comment by oiwn** [comment]
> Hi @iammeosjin, we don't currently have a Bulk Write implementation in the driver but we have had regular discussions about pursuing this in the future. In the meantime, please feel free to watch this existing issue to keep track of this: https://jira.mongodb.org/browse/RUST-531
> 
> Thank you for submitting this issue!

there is another one https://jira.mongodb.org/browse/RUST-271

Discussion end up with promise to discuss API and implement "later this year".
