### ISSUE TITLE
Cursor iterator returns Error with InvalidResponse "invalid type: unit value, expected a string"

### ISSUE THREAD

**Issue by belohnung** [mongodb/mongo-rust-driver#479]
```rust
use mongodb::bson::Document;
use mongodb::{bson::doc, sync::Client};
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
struct ASNEntry {
    asn: i32,
    mode: String,
    name: String,
    description: String,
    prefixes: Vec<PrefixEntry>,
}

#[derive(Debug, Serialize, Deserialize)]
struct PrefixEntry {
    prefix: String,
    name: String,
    countryCode: Option<String>,
    description: String,
}

fn main() {
    let client = Client::with_uri_str("mongodb://mongodb.intern.ninjahub.net:27017").unwrap();
    let database = client.database("censored");
    let collection = database.collection::<ASNEntry>("censored");
    let cursor = collection.find(doc! {}, None).unwrap();
    for result in cursor {
        dbg!(result);
    }
}
```

When using the integrated deserialization feature the 102nd Document returns this:

```
[src/main.rs:29] result = Err(
    Error {
        kind: InvalidResponse {
            message: "invalid type: unit value, expected a string",
        },
        labels: {},
    },
)
[src/main.rs:29] result = Err(
    Error {
        kind: Command(
            CommandError {
                code: 43,
                code_name: "CursorNotFound",
                message: "cursor id 7287796362393293625 not found",
            },
        ),
        labels: {},
    },
)

```

**Comment by tommycodebox** [comment]
I am also facing this issue using async API with `find_one` which seems to be using `find` under the hood, but in my case Im passing non-empty valid document filter which works well in Compass

**Comment by isabelatkinson** [comment]
@belohnung do you have any further questions or comments regarding this issue? In addition to the debugging strategies mentioned above, you can change the `batch_size` configured for your `find` operation to 1 in order to deserialize the documents returned from your collection one at a time.

**Comment by belohnung** [comment]
well this is still a bug in the batch deserializer as it seems

**Comment by isabelatkinson** [comment]
@belohnung Can you elaborate? Does the deserialization work when you change `batchSize` to 1?

**Comment by belohnung** [comment]
i don't have much time right now, once i find some i will try

**Comment by isabelatkinson** [comment]
Hi @vexy, thank you for the additional information! To clarify, the purpose of using the `batch_size` option in this context is to isolate which document being returned is causing deserialization issues. When `batch_size` is set to 1, each document will be deserialized individually which allows you to isolate which document is causing the deserialization errors.

> Setting `batch_size(1)` in `FindOptions` parameter and passing it to a regular `find(...)` method may either succeed or fail randomly.

Are you seeing `InvalidResponse` failures similar to the ones detailed above? Have you been able to determine which documents are causing these errors?

I'd recommend attempting the same `find` operations you've detailed above on a `Collection<Document>`. This will allow you to inspect the un-deserialized documents being returned from your database to verify that they match the schema you've defined. You can also try to convert them to your type using [`from_document`](https://docs.rs/bson/latest/bson/fn.from_document.html). Something along the lines of:

```
let find_options = FindOptions::builder().batch_size(1).build();
let document_collection = collection.clone_with_type::<Document>();
let cursor = document_collection.find(None, find_options).await?;
while let Some(doc) = cursor.try_next().await? {
    // inspect the document returned and attempt to convert it to your defined type
}
```

**Comment by vexy** [comment]
Hello @isabelatkinson, I've finally had some time to tryout your suggestion.

It turned out that my problem and weird error messages were due to the nature of the underlying document fields. Just as you suggested 💪   

Long story short some document fields had to be structured as `Option<Type>` instead of just `Type`.
More specifically, this is what was causing trouble (_pseudo-struct_):
```rust
struct NoGo {
    id: ObjectId,
    name: String,  //if there are fields in document that do not have 'name'
}

struct WillWork {
    id: ObjectId,
    name: Option<String>,  //wrap missing fields with Option<T> type
}
```

Anyhow, thank you for your support 🙏
