### ISSUE TITLE
Concurrent session calls

### ISSUE THREAD

**Issue by maxmishkoy** [mongodb/mongo-rust-driver#481]
As per my issue mentioned here:
https://stackoverflow.com/questions/69476422/try-join-to-make-mongodb-transactions-sent-at-the-same-time

I would like to make the concurrent transaction as in MongoDB Node.js driver, but looks like the Rust driver has some limitations in session and transaction functionality. DB.update_many is not a solution when you want to use different collections concurrently. 

Wondering if it could be fixed or if there are different approaches. 
Thanks!

**Comment by patrickfreed** [comment]
This limitation is actually by design. In MongoDB, client sessions cannot be used concurrently (see [here](https://docs.mongodb.com/manual/core/read-isolation-consistency-recency/#client-sessions-and-causal-consistency-guarantees) and [here](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#clientsession)), and so in the Rust driver we accept them as `&mut` to prevent this from happening at compile time. The Node example is only working by chance and is definitely not recommended or supported behavior. If you would like to perform both updates as part of a transaction, you'll have to run one update after the other. If you'd like to run them concurrently, you'll need to execute them without a session or transaction.

As a side note, a client session can only be used with the client that it was created from. In the provided example, the session is being used with a different one, which will cause an error.

I hope this helps, please let us know if you have any further questions!

(I cross-posted this response to SO too in case future readers there are interested).

**Comment by xxated** [comment]
Thanks a lot for the information you've provided us! I missed it while
doing my research. Btw, i posted few comments and the research to the
question for self interest. Here it is:
https://stackoverflow.com/questions/69476422/try-join-to-make-mongodb-transactions-sent-at-the-same-time/69504359#69504359

Also, just out of my curiosity, I have 2 more questions left:
1) is Rust driver planning to implement withTransaction() functionality? I
saw a ticket for it, bit it seems to be forgotten... It will be very
helpful for sending 1 whole transactional function to the mongodb instead
of awaiting for each write sequentially.
2) Is mongodb planning to provide concurrent session writes in next
versions?

Thanks a lot for all your help and support!
We're happy to be in team where we're always supposed!

Thanks again,
Best regards, Max

**Comment by xxated** [comment]
@patrickfreed Thanks for your answers!
Btw, I've implemented some helpers that are based on the expected withTransaction() functionality and tested it in my project.
There is my working solution that might be helpful for you guys to accomplish withTransaction. It is based on the provided example in the rust-driver documentation.

```
use crate::{MyError, DB_CLIENT};
use async_graphql::{ErrorExtensions, Result};
use futures::Future;
use lazy_static::lazy_static;
use mongodb::{
    error::{TRANSIENT_TRANSACTION_ERROR, UNKNOWN_TRANSACTION_COMMIT_RESULT},
    options, ClientSession,
};
use std::time::Duration;

lazy_static! {
    // to use for reads
    pub static ref TRANSACTION_PRIMARY_OPTIONS: options::TransactionOptions = options::TransactionOptions::builder()
            .read_concern(Some(options::ReadConcern::majority()))
            .write_concern(Some(
                options::WriteConcern::builder()
                    .w(Some(options::Acknowledgment::Majority))
                    .w_timeout(Some(Duration::new(3, 0)))
                    .journal(Some(false))
                    .build(),
            ))
            .selection_criteria(Some(options::SelectionCriteria::ReadPreference(
                options::ReadPreference::Primary
            )))
            .max_commit_time(Some(Duration::new(3, 0)))
            .build();

    // to use for writes
    pub static ref TRANSACTION_NEAREST_OPTIONS: options::TransactionOptions = options::TransactionOptions::builder()
            .read_concern(Some(options::ReadConcern::majority()))
            .write_concern(Some(
                options::WriteConcern::builder()
                    .w(Some(options::Acknowledgment::Majority))
                    .w_timeout(Some(Duration::new(3, 0)))
                    .journal(Some(false))
                    .build(),
            ))
            .selection_criteria(Some(options::SelectionCriteria::ReadPreference(
                options::ReadPreference::Nearest {
                    options: options::ReadPreferenceOptions::builder()
                        //TODO: setup mongol locally and give names (tags) to members in replica set
                        .tag_sets(None)
                        .max_staleness(Some(Duration::new(3, 0)))
                        .hedge(Some(options::HedgedReadOptions::with_enabled(true)))
                        .build()
                },
            )))
            .max_commit_time(Some(Duration::new(3, 0)))
            .build();
}

pub async fn create_session_and_start_transaction<'a>(is_find: bool) -> Result<ClientSession> {
    let transaction_options = if is_find {
        (*TRANSACTION_PRIMARY_OPTIONS).clone()
    } else {
        (*TRANSACTION_NEAREST_OPTIONS).clone()
    };

    let session_options = options::SessionOptions::builder()
        .snapshot(Some(false))
        .default_transaction_options(None)
        .build();

    let mut session = DB_CLIENT
        .get()
        .await
        .start_session(Some(session_options))
        .await?;

    session.start_transaction(Some(transaction_options)).await?;

    Ok(session)
}

pub async fn execute_transaction<R, AsyncFunction, FnResponse>(
    transaction: AsyncFunction,
) -> Result<R>
where
    AsyncFunction: Fn() -> FnResponse,
    FnResponse: Future<Output = Result<R>>,
{
    loop {
        let result = transaction().await;

        match result {
            Ok(response) => return Ok(response),
            Err(err) => {
                if err.message.contains(TRANSIENT_TRANSACTION_ERROR) {
                    //should try again if unexpected error
                    continue;
                } else {
                    //if other kind of errors, return it
                    return Err(err);
                }
            }
        }
    }
}

pub async fn commit_transaction(session: &mut ClientSession) -> Result<()> {
    loop {
        let result = session.commit_transaction().await;
        if let Err(ref error) = result {
            if error.contains_label(UNKNOWN_TRANSACTION_COMMIT_RESULT) {
                //should try again if unexpected error
                continue;
            }
        }
        match result {
            Ok(_) => return Ok(()),
            Err(err) => return Err(MyError::ServerError(err.to_string()).extend()),
        };
    }
}

```

And the mutation to use it:

```
async fn example_mutatio(
        &self,
        current_user_id: ObjectId
    ) -> Result<bool> {
 
        //here DB is global variable and is implemented from DB_CLIENT, which is another global variable
        //it works because they're suing the same client
        let db = DB.get().await.collection::<Document>("users");

        let transaction = || async {
            let mut session = create_session_and_start_transaction(false).await?;


            db.update_one_with_session(
                doc! {
                    "_id": current_user_id
                },
                doc! {
                    "$inc": {
                        "number": -1
                    }
                },
                None,
                &mut session,
            )
            .await?;

           //all other mutations you want to include using session

            commit_transaction(&mut session).await?;
            
            //can return anything you want, usually, it is the mutation response
            return Ok(true);
        };

        Ok(execute_transaction(transaction).await?.into())

    }
```

execute_transaction is sort of withTransaction() custom helper.

The only difference between here and official documentation is that session is defined inside the `withTransaction` and not outside, so in the case of TRANSIENT_TRANSACTION_ERROR it will re-define the session again... 
 
This code works as expected (but wasn't tried within all possible cases), but is currently in development. Just wanted to share my solution with you so it might be helpful.
Thanks!
