### ISSUE TITLE
SendError when reusing the Client

### ISSUE THREAD

**Issue by robinchm** [mongodb/mongo-rust-driver#509]
Hi I am fairly new to the rust language and just finished the book. Here I am trying to wrap the mongodb client for later usage, but invoking the wrapped client panics the application. My `Cargo.toml` is:

```toml
[dependencies]
tokio = "1.13.0"
bson = "2.0.1"
mongodb = "2.0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
```

And my code looks like:
```rust
use futures::stream::TryStreamExt;
use mongodb::{
    bson::doc,
    options::{ClientOptions, FindOptions},
    Client, Database,
};
use serde::{Deserialize, Serialize};

// This is the wrapper around the mongo Client
struct Backend {
    client: Client,
}

// This is the document type
#[derive(Debug, Serialize, Deserialize)]
struct Data {
    date: String,
}

impl Backend {
    #[tokio::main]
    pub async fn test(&self) {
        let mut cursor = self
            .client
            .database("a")
            .collection::<Data>("date")
            .find(doc! { "date" : "2021-01-01" }, None)
            .await
            .expect("find error");
        while let Some(s) = cursor.try_next().await.unwrap() {
            println!("{:#?}", s)
        }
    }

    #[tokio::main]
    pub async fn new(url: &str) -> Result<Backend, mongodb::error::Error> {
        let client_options = ClientOptions::parse(url).await?;
        let client = Client::with_options(client_options)?;
        client
            .database("admin")
            .run_command(doc! {"ping": 1}, None)
            .await?;
        let b = Backend { client: client };
        let mut cursor = b
            .client
            .database("a")
            .collection::<Temp>("date")
            .find(doc! { "date" : "2021-01-01" }, None)
            .await
            .expect("find error");
        while let Some(s) = cursor.try_next().await.unwrap() {
            println!("{:#?}", s)
        }
        Ok(b)
    }
}

fn main() {
    let b = Backend::new("mongodb://localhost:3306").expect("cannot connect to mongo backend.");
    b.test();
}
```

What I am trying to do here is to create a wrapper around the client, and to reuse that wrapper in multiple places. The wrapper is created in the `async fn new` function, which moves the mongo client into the wrapper struct. In this function a find command is also executed to make sure the client is working.

Then when I called the `test` method on the wrapper, which is supposed to dispatch the same find command using the same client, the application panics with the following message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) })', ~/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/mongodb-2.0.1/src/cmap/connection_requester.rs:43:34
```

I have no idea why the same find command works in the `new` function but not in the `test` function? I suspect I made some silly mistake with the async runtime, but the error message does not point me anywhere and searching it yields few results. Have spent hours but still can't figure it out.

Would appreciate your help!

**Comment by patrickfreed** [comment]
Hi @robinchm!

The issue here is in the usage of `#[tokio::main]`. This macro is intended only to be used at the entry point of your application (i.e. around `fn main`). Under the hood it basically just creates a tokio runtime and then tells it to execute your async function.

In your example, each of `Backend::new` and `Backend::test` use `tokio::main` and thus are creating their own runtimes. The error you're seeing I believe is a result of one of the runtimes being dropped while the client is still open.

To solve this, remove the `tokio::main` wrappers around `new` and `test` and instead add it to `fn main`. As part of that you'll need to annotate `main` as `async`.

Let me know if this solves your issue or if you have any further questions!

**Comment by robinchm** [comment]
@patrickfreed Yes that seems to be the reason. After annotating the main only and some other adjustments it works fine.

However I want to encapsulate the async calls below a certain level so where the data are used in calculation does not need to be aware of the async nature of db access. So far I am going by the sync access method.
