### ISSUE TITLE
Connecting with the x509 certificate(s) doesn't seem to be possible.

### ISSUE THREAD

**Issue by Zageron** [mongodb/mongo-rust-driver#527]
https://github.com/mongodb/mongo-rust-driver/blob/master/tests/connection_snippets.rs

1. Create new account using certificate as authentication option.
2. Download certificate
3. Extract the crt and key file
4. Try to use, get unwrap() error when trying to find the certificate files to connct.

Any functional examples? Does the downloaded cert chain not work?

**Comment by abr-egn** [comment]
Hi!  Can you share the exact error message and, if possible, the code you're using to set up the client?

**Comment by Zageron** [comment]
> Hi!  Can you share the exact error message and, if possible, the code you're using to set up the client?

Sure. What are the recommended commands for extracting the CA and key out of the pem that is supplied?

**Comment by abr-egn** [comment]
It turns out that there are two related issues in the driver currently related to x509 authentication, I've filed https://jira.mongodb.org/browse/RUST-1122 to track them.  We'll get a fix in shortly and roll it out with the next release.

**Comment by Zageron** [comment]
> It turns out that there are two related issues in the driver currently related to x509 authentication, I've filed https://jira.mongodb.org/browse/RUST-1122 to track them. We'll get a fix in shortly and roll it out with the next release.

Ah perfect, this bug describes exactly the confusion I was facing. Thank you! :D

**Comment by Zageron** [comment]
Fixed.
