### ISSUE TITLE
WriteConflict error

### ISSUE THREAD

**Issue by gy0801151351** [mongodb/mongo-rust-driver#533]
While using the method "find_one_and_update_with_session", I  got an error with message "Command failed (WriteConflict): WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.".
This offen happens when I take stress testing with concurrency.  The version of mongo-rust-driver is "2.0.2". The version of mongodb server is "4.4.4".

**Comment by abr-egn** [comment]
Hi!  This is likely not related to the Rust driver - that's a server-side error message indicating that your topology can't handle the concurrent load of your stress test; this is especially likely if your testing infrastructure performs a large number of operations per transaction.

**Comment by gy0801151351** [comment]
Why do you say that? I also do the same stress test by java driver of mongodb. It works fine!
If you insist that this is not a driver issue, I will not use this rust driver and not use mongodb in my rust program.

**Comment by abr-egn** [comment]
Can you share a sample of the Rust stress test and the equivalent Java code?  If you're using the [convenient transactions API](https://github.com/mongodb/specifications/blob/master/source/transactions-convenient-api/transactions-convenient-api.rst) in Java, this may be hiding those errors by automatically retrying.  The Rust driver doesn't yet have an implementation of that API, but you can [manually retry](https://docs.mongodb.com/v4.0/core/transactions/#retry-transaction); the Rust equivalent of those examples would be something like

```Rust
fn run_transaction_with_retry<T, F>(txn_func: F, session: &mut ClientSession) -> Result<T>
where
    F: FnMut(&mut ClientSession) -> Result<T>
{
  loop {
    let out = txn_func(&mut session);
    if matches!(out, Err(e) if e.contains_label("TransientTransactionError")) {
      continue;
    }
    return out;
  }
}
```
