### ISSUE TITLE
Migrations or Schema Management Recommendations?

### ISSUE THREAD

**Issue by Zageron** [mongodb/mongo-rust-driver#534]
I've found plenty of ORMs with mongo support that have migrations, and I've dealt with migrations in SQL before.
Does mongo have a recommended methodology for dealing with changing object schemas? Searching hasn't brought up many good, or modern, examples of dealing with varying objects. The best methodology I have found has been a just in time style, where when a piece of data is written to or read from, the "schema version" is tested and if it is out of date it the application updates it. But I could see that getting exceptionally messy regardless of how well it was implemented.

Does anyone have any ideas or know how they could share in this area?

**Comment by bajanam** [comment]
Hi there, thank you for reaching out. This sounds more like a general MongoDB support issue than anything specific to the Rust driver, please reach out to our MongoDB community portal, located [here|https://developer.mongodb.com/community/forums/]

Thank you!

**Comment by Zageron** [comment]
@bajanam No this is most definitely a question for this driver. I'm looking for Rust implementations or examples of migrations that people have found to work effectively.

**Comment by kmahar** [comment]
Hey @Zageron, to clarify, generally we use issues on both our GitHub and Jira projects for tracking feature requests and bug reports. For general discussion and questions around how to use MongoDB and the driver, we ask that our users use the community forums. While you are looking for Rust examples in particular, much of the advice around strategies for migration and schema management for MongoDB applies across languages so you may get some helpful insight from users of various languages including Rust there.

**Comment by seanpianka** [comment]
In case anyone else lands here looking for a direct link about how to migrate and manage your app's data/schema, you can start here: [Merge customer database with upgraded version without data loss](https://www.mongodb.com/community/forums/t/merge-customer-database-with-upgraded-version-without-data-loss/133424)
