### ISSUE TITLE
Mongodb Rust - view all records inside a collection (table)

### ISSUE THREAD

**Issue by sm8082** [mongodb/mongo-rust-driver#540]
**Main.rs...**
extern crate actix_web;
use bson::Bson;
use bson::oid::ObjectId;
use mongodb::bson::{doc};
use serde::{self, Deserialize, Serialize};
use mongodb::{Client};

#[derive(Deserialize, Serialize)]
#[derive(Debug)]
struct Product {
    #[serde(rename = "_id")]
    id: ObjectId,
    item: String,
}

#[actix_rt::main]
async fn main() -> mongodb::error::Result<()> {    

    let  client = Client::with_uri_str("mongodb+srv://sm8082:*******@cluster0.zemkn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority").await.expect("Mongo Error");
    let  db = client.database("example");
    let  collection = db.collection::<Product>("products");
    println!("Adding record...");

    let mut cursor = collection.find(None, None).await;
    
    while let Some(doc) = cursor.next().await {
        let prod: Product = bson::from_bson(Bson::Document(doc?))?;
        println!("{}: {}", prod.id, prod.item);
    }

    Ok(())
}

------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Cargo.toml dependencies:**

[dependencies]
actix-web = "3.0.0"
actix-rt = "1.0.0"
bson = "0.14.1"
serde_json = "1.0"
tokio = {version="1.11.0", features=["full"]}
serde = { version = "1.0", features = ["derive"] }
futures = "0.1.29"
#futures = "0.3.12"
[dependencies.mongodb]
version = "2.0.0"
default-features = false
features = ["async-std-runtime"]

---------------------------------------------------------------------------------------------------------------------------------------
**Error screen as below:**

error[E0599]: no method named `next` found for enum `Result` in the current scope
  --> src/main.rs:26:34
   |
26 |     while let Some(doc) = cursor.next().await {
   |                                  ^^^^ method not found in `Result<mongodb::Cursor<Product>, mongodb::error::Error>`

error[E0277]: `?` couldn't convert the error to `mongodb::error::ErrorKind`
   --> src/main.rs:27:66
    |
27  |         let prod: Product = bson::from_bson(Bson::Document(doc?))?;
    |                                                                  ^ the trait `From<DecoderError>` is not implemented for `mongodb::error::ErrorKind`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <mongodb::error::ErrorKind as From<mongodb::bson::de::Error>>
              <mongodb::error::ErrorKind as From<mongodb::bson::ser::Error>>
              <mongodb::error::ErrorKind as From<std::io::Error>>
              <mongodb::error::ErrorKind as From<std::io::ErrorKind>>
    = note: required because of the requirements on the impl of `From<DecoderError>` for `mongodb::error::Error`
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, DecoderError>>` for `Result<(), mongodb::error::Error>`
note: required by `from_residual`
   --> /home/sm8082/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/try_trait.rs:339:5
    |
339 |     fn from_residual(residual: R) -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `Ch13_Mongodb_BSON_display_data` due to 2 previous errors

**Comment by bajanam** [comment]
Hi @sm8082 thanks for reaching out.  Our team is currently off for the holidays but we will review this upon their return next year.

**Comment by abr-egn** [comment]
Hi!

The `next` method is provided by the `futures::stream::StreamExt` trait; if you include that in your use statements that should resolve this error.  The [documentation](https://docs.rs/mongodb/2.1.0/mongodb/struct.Cursor.html) for `Cursor` has some helpful examples here.
