### ISSUE TITLE
Documentation: Updating example

### ISSUE THREAD

**Issue by GreeFine** [mongodb/mongo-rust-driver#542]
I just had a lot of trouble finding how to update a document in my collection, which has a value that isn't primitive (a structure here in my example).

I was trying to set the "oders" fields.
And I had to look for some time to find that you can use `bson::to_bson` to Sereliaze the structure.
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Turtle {
    name: String,
    pub orders: Vec<Command>,
    pub infos: HashMap<String, String>,
    pos: Position,
    facing: Facing,
}


let result = turtles
        .update_one(
            doc! { "name": &name },
            doc! { "$set": { "orders": bson::to_bson(&orders).expect("Unable to convert orders to bson") } },
            None,
        )
        .await
        .expect("Unable to update orders of the turtle");
```

Could we add an example about `bson::to_bson` and perhaps also about updating in the README.md usage section ?
I can do it and open a Pull requests if it helps 👍

**Comment by bajanam** [comment]
Hey @GreeFine thanks for your interest and feedback, the team is off until next year but we always welcome PRs from the community.  We will review open PRs based on our development workload when the team returns.

**Comment by GreeFine** [comment]
Hi @bajanam, I made the PR.
Do you have any news, or idea on when it's could be reviewed?

**Comment by bajanam** [comment]
Closing per comments on PR #560
