### ISSUE TITLE
Add function for ping command

### ISSUE THREAD

**Issue by ISibboI** [mongodb/mongo-rust-driver#544]
The ping command is useful to check if the database cluster is available.

While it can be easily checked with `database.run_command(doc! {"ping": 1}, None).is_ok()`, it would be nice to be able to simply call `database.ping().is_ok()`.

**Comment by abr-egn** [comment]
Hi!

We appreciate the suggestion - however, we have to carefully weigh what functionality we build into the API because we place a high priority on API stability.  In this case, because the added utility is very minor it's unlikely to be something we'll want to turn into an API commitment.
