### ISSUE TITLE
RUST-488 Allow sync and async to coexist

### ISSUE THREAD

**Issue by AaronErhardt** [mongodb/mongo-rust-driver#550]
If you use a crate that uses the sync API and another crate that uses the async API you won't be able to compile. However, the async part is always compiled even when the sync feature is active, it's just not exposed as public.

This seems like an artificial and unnecessary limitation. It should be easy to expose both APIs.

Also, despite the docs saying it's not possible, you can in fact enable both sync and async-std-runtime as features without compiler errors. Yet, in this case only the sync API will work. Having sync and tokio-runtime enabled does what the docs say and throws an error but very late so it's hard to detect.

**Comment by patrickfreed** [comment]
Hi @AaronErhardt, thanks for filing this issue!

We discussed this with the team and agree that this limitation isn't necessary and can be removed in the future. You can follow RUST-488 to track progress on this. Thanks again!

**Comment by kmahar** [comment]
Hi @AaronErhardt, we released support for this today via our [2.3.0-beta](https://github.com/mongodb/mongo-rust-driver/releases/tag/v2.3.0-beta) release, so I am going to close out this issue. If you try it out and have any feedback or run into any issues please let us know!
