### ISSUE TITLE
TimeseriesOptions is impossible to use

### ISSUE THREAD

**Issue by fuwaneko** [mongodb/mongo-rust-driver#556]
I was trying to create timeseries collection via driver and found that it's not possible since TimeseriesOptions is marked as non-exhaustive so there's no way to instantiate that structure outside mongodb crate. Please, either add derive(Default) or create a function to instantiate TimeseriesOptions struct.

**Comment by isabelatkinson** [comment]
Hi @fuwaneko, thank you for filing this issue! Our options derive the `TypedBuilder` trait so that users can use the builder pattern to constructs options, but it looks like that was unintentionally omitted from `TimeseriesOptions`. I created #557 to fix this.

**Comment by isabelatkinson** [comment]
@fuwaneko The fix for this has been merged and will be included in the next release. Thanks again for filing this issue!
