### ISSUE TITLE
Possible issue with generic parameterization of collections

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [mongodb/mongo-rust-driver#574]
A simple application [`find_one_and_update`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find_one_and_update) might be to update an item in an array within a document and return the old item (given our document may be large and we don't want to transfer all of it).

You might do this like:
```rust
let update_result = user_collection.find_one_and_update(
    doc! { "_id": doc_id, "items.item_id": &item_id },
    mongodb::options::UpdateModifications::Document(
        doc! { "$set": { "items.$.data": 12 } },
    ),
    mongodb::options::FindOneAndUpdateOptions::builder()
        .projection(doc! {
            "item": {
                "$arrayElemAt": ["$items", {
                    "$indexOfArray": ["$items.item_id",&item_id]
                } ]
            }
        })
        .build(),
).await;
```
This may work if we have `Collection<Document>` as `update_result` would be `Result<Option<Document>>` which would allow for projection. But as soon as we use a specific model [as recommend](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#):

> It is recommended to define types that model your data which you can parameterize your Collections with instead of Document

We can no longer use projection in any of the operations on `Collection` which return a type parameterised with `T` (e.g. [`find_one_and_update`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find_one_and_update), [`find_one`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find_one), [`find_one_and_replace`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find_one_and_replace), etc.).

If I'm missing something here please let me know but this seems like a fairly significant design issue.

A fairly easy solution might be to simply return `impl From<Document>` or `impl TryFrom<Document>` or `impl Deserialize` for [`find_one_and_update`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.find_one_and_update) etc. Notably this same approach could be applied to [`aggregate`](https://docs.rs/mongodb/latest/mongodb/struct.Collection.html#method.aggregate) to return `Cursor<K>` instead of `Cursor<Document>`.

**Comment by patrickfreed** [comment]
In general, we do recommend using models for your data, and when not using projection (e.g. for inserts or for reads of full documents), you can just use a `Collection<T>` where `T` contains all of the document's fields. If you'd like to project some out, you can define another type which has a subset of the fields (or use `Option` for the fields that might be projected out) for operations which don't require them. The method `Collection::clone_with_type` helps facilitate this for one-off operations.

e.g.
```rust
#[derive(Deserialize, Serialize)]
struct FullDoc {
    name: String,
    age: i32,
    location: String,
}

#[derive(Deserialize, Serialize)]
struct PartialDoc {
    name: String,
}

let collection = db.collection::<FullDoc>("doc");
// insert some full data
collection.insert_one(FullDoc { ... }, None).await?;

// only want partial doc here
let update_result = collection.clone_with_type::<PartialDoc>().find_one_and_update(
    doc! { "name": "Bob" },
    mongodb::options::UpdateModifications::Document(
        doc! { "$set": { "age": 12 } },
    ),
    mongodb::options::FindOneAndUpdateOptions::builder()
        .projection(doc! { "name": 1 })
        .build(),
).await?;
```
Note that `Collection` doesn't cache any values of type `T`, so this cloning is essentially free. The parameter on `Collection` is only there to determine which `T` is used in the return values of the various CRUD methods (e.g. `find` returns a `Cursor<T>`).

In the next release `2.2.0`, cursors will also have this functionaltiy, so you can use projection in `find` or `aggregate` and then change the cursor accordingly:

```rust
let options = FindOptions::projection(doc! { "name": 1 }).build();
let mut cursor = collection.find(None, options).await?.with_type::<PartialDoc>();
```

**Comment by itsfarseen** [comment]
@patrickfreed A better design would be to move the type parameter from `Collection<T>` to individual functions `find_one<T>()`, `insert_one<T>()`.

This is no worse than the current solution in terms of "If It Compiles It Probably Runs", while being slightly more ergonomic.

If we want maximum safety in terms of "If It Compiles It Probably Runs", we should define something like this:

```rust
trait ProjectFrom<T> {
  fn projection() -> bson::Document;
}

struct MyDocument {
   _id: ObjectId,
   foo: String,
   bar: String,
}

impl_projection!(MyDocumentFooOnly, MyDocument { foo })

// the macro expands to something like the following snippet:

struct MyDocumentFooOnly { foo: String } 
impl ProjectFrom<MyDocument> for MyDocumentFooOnly {
  fn projection() {
    doc!{"foo": 1}
  }
}

// the macro could even create some tests
#[cfg(test)]
fn test_project_my_document_foo_only() {
   let my_document = MyDocument { _id: <random-id>, foo: <random-string>, bar: <random-string> }; // there are crates to generate random values for strings and byte arrays, I believe.
   let projected = mongodb::utils::project(my_document);
   assert_eq!(projected, MyDocumentFooOnly { foo: my_document.foo });
}

// Then Collection<T> becomes:


impl Collection<T> {
   insert_one(&self, doc: T);
   find_one<U: ProjectFrom<T>>(&self) -> Result<U>;
}

```
