### ISSUE TITLE
Get element by '_id' deprecated? 

### ISSUE THREAD

**Issue by DerZwergGimli** [mongodb/mongo-rust-driver#589]
I would like to know if in the current version 2.1 the possibility to get an element by id is deprecated? 
I can not find a hint hint in the documenation on how to get an element by the _id field.

```
match collection
        .find_one(doc! { "_id": mongodb::oid::ObjectId::with_uri_str(&id)  }, None)
        .await
        { 
           [...]
        }
```
(id here is a String)

**Comment by DerZwergGimli** [comment]
ok i think i found my issue

```rust 
 match collection
        .find_one(doc! { "_id": bson::oid::ObjectId::parse_str(&id).unwrap()  }, None)
        .await
    {
      [...]
    }
```

is this the correct way now? Are we supposed to use bson?
If yes this issue can be closed! 
Thanks

**Comment by patrickfreed** [comment]
Yep, `ObjectId::parse_str` is the correct way to create an `ObjectId` from a string in `bson` 2.0+. In 1.0 it used to be `ObjectId::with_uri_str` but was renamed to more closely match the API of the `uuid` crate.
