### ISSUE TITLE
Querying takes an extremely long time

### ISSUE THREAD

**Issue by Milo123459** [mongodb/mongo-rust-driver#612]
## Versions/Environment
1. What version of Rust are you using? 1.59.0
2. What operating system are you using? Windows
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) 
https://github.com/rust-lang/crates.io-index#mongodb:2.1.0
https://github.com/rust-lang/crates.io-index#bson:2.1.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 4.4.6
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? Not sure

## Describe the bug

**BE SPECIFIC**:
It is expected that the query can be executed within 5-10 seconds, when in reality it takes about 30.
* If you know how to reproduce this bug, please include a code snippet here:
```rs
	let finder = FindOptions::builder()
		.sort(doc! {
			"lastUpdate": 1
		})
		.limit(118)
		.build();
	let mut cursor = db.find(doc! {
        "lastUpdate": {
            "$lte": DateTime::from_chrono::<chrono::Utc>(chrono::DateTime::from_utc(chrono::NaiveDateTime::from_timestamp(DateTime::now().to_chrono().timestamp_millis() - 24 * 60 * 60 * 1000, 0), chrono::Utc))
        }
    }, finder).await.unwrap();
	while let Some(doc) = cursor.try_next().await.unwrap() {
		println!("id: {} lastUpdate: {:?}", doc._id, doc.lastUpdate);
	}
```

**Comment by Milo123459** [comment]
I also have a cron that runs every minute. This is managing to make the corn sadly fall behind because of how long the query is taking.

**Comment by kmahar** [comment]
Hi @Milo123459, thanks for reaching out. Is it possible that you are being affected by the issue described [here](https://github.com/mongodb/mongo-rust-driver#windows-dns-note)?

**Comment by Milo123459** [comment]
Ah right, yes - I believe that is causing it. 

I also have another issue, should I make a new issue?

**Comment by kmahar** [comment]
Cool - let me know if switching the DNS resolver config fixes it, if so I will close this issue.

And yes, if it is separate please create a new issue. Thanks!

**Comment by Milo123459** [comment]
It did fix it! I'll make a new issue.
