### ISSUE TITLE
Running multiple test failes, running tests one by one works

### ISSUE THREAD

**Issue by AaronErhardt** [mongodb/mongo-rust-driver#615]
## Versions/Environment
1. rustc 1.59.0
2. Windows 10
3. mongodb and bson 2.1.0 from crates.io
4. 5.0.6 
5. MongoDB topology: standalone

## Describe the bug

When I run multiple tests, some test cases fail most of the time. When I run the same tests one by one they work perfectly fine.

The errors indicate that there's some issue with senders and receivers and cancelled futures. Once the first test fails, it seems to poison all following tests.

It looks like the behavior is caused by [`src\cmap\connection_requester.rs`](https://github.com/mongodb/mongo-rust-driver/blob/master/src/cmap/connection_requester.rs)

#### Test output:

```
failures:

---- database::filters::mechanical::test::test_name_filter stdout ----
thread 'database::filters::mechanical::test::test_name_filter' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', C:\Users\ERHAAAR\.cargo\registry\src\github.com-1ecc6299db9ec823\mongodb-2.1.0\src\cmap\connection_requester.rs:43:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- database::filters::mechanical::test::test_stack_filter stdout ----
thread 'database::filters::mechanical::test::test_stack_filter' panicked at 'called `Result::unwrap()` 
on an `Err` value: SendError(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) })', 
C:\Users\ERHAAAR\.cargo\registry\src\github.com-1ecc6299db9ec823\mongodb-2.1.0\src\cmap\connection_requester.rs:39:34

---- database::filters::mechanical::test::test_diameter_filter stdout ----
thread 'database::filters::mechanical::test::test_diameter_filter' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', C:\Users\ERHAAAR\.cargo\registry\src\github.com-1ecc6299db9ec823\mongodb-2.1.0\src\cmap\connection_requester.rs:43:24

---- database::filters::characteristics::test::test_characteristics_filter stdout ----
thread 'database::filters::characteristics::test::test_characteristics_filter' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', C:\Users\ERHAAAR\.cargo\registry\src\github.com-1ecc6299db9ec823\mongodb-2.1.0\src\cmap\connection_requester.rs:43:24

---- simulation::tests::test_impossible_s_selecion stdout ----
thread 'simulation::tests::test_impossible_s_selecion' panicked at 'called `Result::unwrap()` on an `Err` value: Database(Error { kind: Io(Custom { kind: Other, 
error: "IO driver has terminated" }), labels: {} })', mechanical\src\simulation\tests.rs:57:10

---- simulation::tests::test_w_selecion stdout ----
thread 'simulation::tests::test_w_selecion' panicked at 'called `Result::unwrap()` on an `Err` value: Database(Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Single, Servers: [ { Address: localhost:27017, Type: Unknown, Error: IO driver has terminated }, ] }" }, labels: {} })', mechanical\src\simulation\tests.rs:90:10

---- simulation::tests::test_s_selecion stdout ----
thread 'simulation::tests::test_s_selecion' panicked at 'called `Result::unwrap()` on an `Err` value: Database(Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Single, Servers: [ { Address: localhost:27017, Type: Unknown, Error: IO driver has terminated }, ] }" }, labels: {} })', mechanical\src\simulation\tests.rs:14:10

---- simulation::tests::test_impossible_w_selecion stdout ----
thread 'simulation::tests::test_impossible_w_selecion' panicked at 'Couldn't find the requested stack length in the database: Database(Error { kind: Io(Custom 
{ kind: Other, error: "IO driver has terminated" }), labels: {} })', mechanical\src\simulation\windings\mod.rs:74:14


failures:
    database::filters::characteristics::test::test_characteristics_filter
    database::filters::mechanical::test::test_diameter_filter
    database::filters::mechanical::test::test_name_filter
    database::filters::mechanical::test::test_stack_filter
    simulation::tests::test_impossible_s_selecion
    simulation::tests::test_impossible_w_selecion
    simulation::tests::test_s_selecion
    simulation::tests::test_w_selecion

test result: FAILED. 14 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 31.47s
```

**To Reproduce**
1. Write a few tests that use the same mongodb database trough a static variable
2. Run all tests with `cargo test`

**Comment by kmahar** [comment]
Hi @AaronErhardt, thank you for reaching out.

> The errors indicate that there's some issue with senders and receivers and canceled futures. 

`Client`s/`Database`s are designed to support concurrent usage, but there are currently some known limitations in the driver regarding its ability to gracefully handle dropping futures -- see this section of the [README](https://github.com/mongodb/mongo-rust-driver#warning-about-timeouts--cancellation) as well as RUST-937 for details. For that reason, we currently highly recommend users poll all futures to completion. 

That said, we're interested in trying to mitigate these types of problems where we can, so we're interested to know more about your tests/see sample code and how you're running into this. Do your tests drop any futures, or are they perhaps getting dropped because the test  fails/aborts for some other reason? What types of driver operations are the tests performing? 

Thanks!

**Comment by AaronErhardt** [comment]
There's no timeout happening AFAICT. I'm using `#[tokio::test]` to run asynchronous test code which doesn't use a timeout.

I've noticed a few more things:

+ The results are not deterministic. The tests fail during 60~80% of all attempts on average while passing just fine in the remaining attempts.
+ Once the first test case failed, the remaining test cases are stuck and won't complete.
+ Removing all uses of `unwrap` doesn't make a difference.
+ Release and debug configurations behave the same.
+ The number of jobs doesn't make a difference (`-j 1` and `-j 4` behave the same).

Potentially the issue is caused by having multiple runtimes as each test has its own.
Or the issue is caused by the global static collection variable.

I've written a small crate that can reproduce the issue with a couple of tests using only `find_one`:

[database_test.zip](https://github.com/mongodb/mongo-rust-driver/files/8408887/database_test.zip)

> You can populate the test database with the tests that were commented out.
> You need to add a `.env` file with something like `DATABASE_URL=mongodb://localhost:27017`

### Example log of a failed attempt of the small example crate

```
    Finished test [unoptimized + debuginfo] target(s) in 0.59s
     Running unittests (C:\Users\...\target\debug\deps\database_test-9590366faf895b0f.exe)

running 4 tests
test test::find_entry_2 ... ok
test test::find_entry_1 ... ok
test test::find_entry_3 ... ok
test test::find_entries ... FAILED

failures:

---- test::find_entries stdout ----
thread 'test::find_entries' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\mongodb-2.1.0\src\cmap\connection_requester.rs:43:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::find_entries

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.81s

error: test failed, to rerun pass '--lib'
```

**Comment by kmahar** [comment]
Thanks for these additional details! 
> Potentially the issue is caused by having multiple runtimes as each test has its own.
Or the issue is caused by the global static collection variable.

I believe the problem is the combination of these two things. A `Client` instance (and those that are created via it such as `Collection`) should only be used with a single runtime instance. It may happen to work sometimes, but we would consider doing this to be undefined behavior.

The fix here would either be to use a static runtime and `#[test]` rather than `#[tokio::test]`, or to create a new `Client` (and then a new `Database` and `Collection` from it) per test instead.

**Comment by AaronErhardt** [comment]
I see. If this isn't considered a bug we should close this issue. 

Yet, it'd be great if this behavior was documented somewhere or even a small macro was added to make it easier to run tests on the same runtime.

**Comment by kmahar** [comment]
I agree we should at least document this somewhere. We're currently working on writing a Rust driver manual as a reference for users and this seems like something to include there - I filed RUST-1259 so we'll remember to mention this.
