### ISSUE TITLE
Update UUID to 1.0.0

### ISSUE THREAD

**Issue by markusgod** [mongodb/mongo-rust-driver#650]
Hey, I don't know where to post, so letting you know here. 
https://github.com/uuid-rs/uuid/releases/tag/1.0.0

**Comment by abr-egn** [comment]
Thanks for bringing this to our attention!  I've opened https://jira.mongodb.org/browse/RUST-1305 to track this.

**Comment by truchi** [comment]
Hello,

Following up on this, [`bson`](https://docs.rs/bson/latest/bson/index.html) has a [`uuid-1`](https://docs.rs/crate/bson/latest/features#uuid-1) feature that you do not "re-export", like you do for [`bson-uuid-0_8`](https://docs.rs/crate/mongodb/latest/features#bson-uuid-0_8).

Thanks

**Comment by kmahar** [comment]
Hi @truchi, we do have such a feature but it has not yet been released: https://github.com/mongodb/mongo-rust-driver/blob/55cd3d90d80df84bd6e7650090cfe7e717b7e70f/Cargo.toml#L60 

For now you can enable the feature directly in bson in your Cargo.toml like:
```
mongodb = "2.3.0"
bson = { version = "2.4.0", features = ["uuid-1"] }
```
