### ISSUE TITLE
Mongodb is panicing when using criterion.rs

### ISSUE THREAD

**Issue by singerxt** [mongodb/mongo-rust-driver#674]
## Versions/Environment
1. What version of Rust are you using? `cargo 1.56.0 (4ed5d137b 2021-10-04).`
3. What operating system are you using? `macOS Monterey 12.4.`
4. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) `https://github.com/rust-lang/crates.io-index#mongodb:2.0.2` `https://github.com/rust-lang/crates.io-index#bson:2.0.1`
5. What version of MongoDB are you using? (Check with the MongoDB shell using `DB.version()`) `4.4.14`
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? `standalone.`

## Describe the bug
I'm trying to use criterion.rs to benchmark my code. I have one function, which is just simply to find documents. When I'm trying to run a benchmark function that is dependent on MongoDB is failing with Panic from the MongoDB library.

```
Benchmarking complete_multipart_upload_bench/complete_multipart_upload/1024: Warming up for 3.0000 sthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) })', /Users/mateuszspiewak/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-2.0.2/src/cmap/connection_requester.rs:43:34
```

Maybe I'm not correctly initializing the MongoDB client?

```rust
use crate::models::tonic::file::File;
use crate::repositories::common::db::{connect_to_collection, Collection, Document};
use async_once::AsyncOnce;
use lazy_static::lazy_static;
use rust_service_error_lib::ServiceError;

type CollectionClient = Collection<File>;

lazy_static! {
    static ref CLIENT: AsyncOnce<CollectionClient> =
        AsyncOnce::new(async { connect_to_collection::<File>("files").await });
}

pub async fn find_one_file(query: Document) -> Result<File, ServiceError> {
    let client = CLIENT.get().await;
    let file_option = client.find_one(query, None).await.map_err(ServiceError::from)?;
    let file = file_option.ok_or_else(|| ServiceError::NotFound("not found".to_string()))?;
    Ok(file)
}
```

**Comment by kmahar** [comment]
Hi @singerxt, thanks for reaching out.

> Maybe I'm not correctly initializing the MongoDB client?

This is possible, but it would be hard to say without seeing your code. Could you share your `connect_to_collection` implementation?

**Comment by singerxt** [comment]
@kmahar of course!

```rust
#[tracing::instrument]
pub async fn connect_to_collection<T>(mongo_db_collection_name: &str) -> Collection<T> {
    let client = get_client().await;

    client.collection::<T>(mongo_db_collection_name)
}

async fn get_client() -> Database {
    // set up database connection pool
    let original_url = env::required("MONGO_URL");
    let mongo_url = add_read_preference(original_url);
    let mongo_db_name = get_mongo_db_name();

    // set timeout
    let mut mongo_db_client_options = ClientOptions::parse(&mongo_url).await.unwrap();
    mongo_db_client_options.server_selection_timeout = Some(Duration::from_secs(5));

    info!("Connecting to database: {}, db name: {}", &mongo_url, &mongo_db_name);

    let client = Client::with_options(mongo_db_client_options).unwrap().database(&mongo_db_name);

    info!("Database connection completed successfully");
    client
}
```

**Comment by kmahar** [comment]
@singerxt Thanks for providing that. That code looks reasonable to me and I think should correctly persist your `Client` and `Collection` instance across usages, so my next suspicion is that you are possibly using a client across multiple async runtime instances, as we've seen users run into similar errors when doing so in the past. 

Might that be the case? Which async runtime are you using (tokio or async-std) and how are you creating/managing the runtime? The design of a `Client` requires that it is only used with a single runtime instance.

In case it's helpful, @patrickfreed actually wrote a [blog post](https://patrickfreed.github.io/rust/2021/10/15/making-slow-rust-code-fast.html) a while back where he was testing the driver using Criterion, with example code [here](https://github.com/patrickfreed/benchmark-example).

**Comment by singerxt** [comment]
That's indeed the source of my problem. I'm spinning runtime for every test. Thank you for providing that feedback it was more than helpful. I probably would not be able to figure it out on my own. 

Thank you so much!

**Comment by kmahar** [comment]
@singerxt Great, I'm glad that was it!
