### ISSUE TITLE
Client fails to connect when run inside rocket.rs

### ISSUE THREAD

**Issue by Anderssorby** [mongodb/mongo-rust-driver#687]
## Versions/Environment
1. What version of Rust are you using? `rustc 1.62.0-nightly (34a6c9f26 2022-04-13)`
2. What operating system are you using? NixOS-22.05 (linux 5.15.47)
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
https://github.com/rust-lang/crates.io-index#mongodb:2.2.2
  bson:1.2.4
  bson:2.3.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
`5.0.9`
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
serverless (Atlas) cluster

## Describe the bug

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
Executing a query or insertion to mongodb
* Do you have any particular output that demonstrates this problem?
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
Nothing I know of
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)? unknown
* If you know how to reproduce this bug, please include a code snippet here:
This works fine in a tokio::main function but not inside a rocket.rs call
```
block_on(async {
        let res = collection.insert_one(data, None).await?;
        });

```

**To Reproduce**
1. Run a mongodb query inside a rocket.rs resolver function.

**Comment by kmahar** [comment]
Hi @Anderssorby, thanks for getting in touch. 

I was not able to reproduce this issue myself from a minimal Rocket application I created using MongoDB so I will need some more information to help investigate what is going on here:

1) Can you provide a more complete code sample that reproduces this issue, including at least:
    * your code to configure the MongoDB client
    * the resolver function
2) What `block_on` method are you using here? Note that Rocket responder functions can be `async`, so it might be reasonable to skip wrapping the query in the `block_on` call, and just mark the responder function `async`. 
3) What is the exact error you're seeing when trying to run your code?

Thank you!

**Comment by Anderssorby** [comment]
Thanks for the swift reply. 
1. I will try to create a minimal reproducing example. It also goes through a juniper graphQL setup. 
2. The block_on is `use futures::executor::block_on;`
Will come back with more details.

**Comment by Anderssorby** [comment]
Using async fuctions and not `block_on` solved it.
Seems like this combination of async and sync is not good. It does not produce any error message or panic however. Just a gridlock (hanging thread) and no response.
But it is a big pitfall that using `block_on` in this context will fail without warning.

**Comment by Anderssorby** [comment]
I guess this could be solved by just having a warning in the docs that you should not use `block_on` to execute mongoDB queries, but this approach does work for other cases. So I guess this can still be called a bug. 
I was using the juniper [execute_sync](https://docs.rs/juniper/latest/juniper/fn.execute_sync.html), but I needed to use [execute](https://docs.rs/juniper/latest/juniper/fn.execute.html). This seems to fix the issue.

**Comment by kmahar** [comment]
I'm glad you were able to solve your issue. I'm not sure that I would call this a bug, I think it is expected. It's hard to say for sure without a repro, but if I had to guess, I think all Rocket responder functions are being run on Tokio tasks, and `futures::executor::block_on` is known and expected to hang when called from a Tokio task (see https://github.com/tokio-rs/tokio/issues/2376 for some related discussion).
