### ISSUE TITLE
the first function takes too long

### ISSUE THREAD

**Issue by ash-hashtag** [mongodb/mongo-rust-driver#694]
## Versions/Environment
1. What version of Rust are you using? 1.61.0
2. What operating system are you using? win 11
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) 2.2.2 run with sync and tokio-runtime same results
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 3.4
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? shared

either I try to connect with options so have to parse it takes too long,
so connect with uri also takes too long like 10-20secs

but from mongodb site it shows that rust driver isn't compatible with mongodb version 3.4, so maybe that has something to do? or else?
But how come it takes that long to just parse uri to clientoptions?
nodejs version works fine tho.

**Comment by kmahar** [comment]
Hi @ash-hashtag, thanks for reaching out.

Are you using a `mongodb+srv` connection string? There is a known issue on Windows with slow DNS resolution in this case which you may be running into. Please see this [section](https://github.com/mongodb/mongo-rust-driver#windows-dns-note) of the README for details and our suggested workaround for the issue. 

That said, you are also correct that the driver does not support MongoDB versions < 3.6.

**Comment by ash-hashtag** [comment]
Thanks, I missed it
