### ISSUE TITLE
the following trait bounds were not satisfied: `mongodb::Cursor<T>: TryStream`

### ISSUE THREAD

**Issue by laik** [mongodb/mongo-rust-driver#700]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/11013552/179664060-750e6ea1-4625-4157-abce-deceadd2d8ee.png">

## Versions/Environment
1. What version of Rust are you using? 
```
 rustc 1.62.0 (a8314ef7d 2022-06-27)
```
3. What operating system are you using? 
4. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
```
https://github.com/rust-lang/crates.io-index#mongodb@2.2.2
https://github.com/rust-lang/crates.io-index#bson@2.3.0
```
5. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?

## Describe the bug

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
* Do you have any particular output that demonstrates this problem?
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
* If you know how to reproduce this bug, please include a code snippet here:
```

```

**To Reproduce**
1. First, do this.
3. Then do this.
4. After doing that, do this.
5. And then, finally, do this.
6. Bug occurs.

**Comment by isabelatkinson** [comment]
Hi @laik, thanks for filing this issue! Do you have the `TryStream` and `TryStreamExt` traits imported from the `futures` crate? You may need to add this to your imports:
```
use futures::stream::{StreamExt, TryStreamExt};
```
Please let me know if this works for you or if the issue persists.

**Comment by isabelatkinson** [comment]
@laik, the solution described in this [forum post](https://www.mongodb.com/community/forums/t/rust-driver-help-writing-a-generic-find-method/168846/2) might be useful to you as well!

**Comment by laik** [comment]
Ok, it has been solved, it is recommended to add documentation
