### ISSUE TITLE
call update_many only update one record?

### ISSUE THREAD

**Issue by adminSxs** [mongodb/mongo-rust-driver#715]
```rust

     for id in ids {
        doc_ids.push((
            "_id".to_string(),
            Bson::ObjectId(oid::ObjectId::parse_str(id).unwrap()),
        ));
    }
     let db = client.database("account");
    let collections = db.collection::<Value>(collect);
    let filter = Document::from_iter(doc_ids.clone());
    let result=  collections.update_many(filter.clone(), doc! {"$set":{"to_ack":to_ack}}, None)
                .await
                .unwrap();
```
only last record updated!

**Comment by isabelatkinson** [comment]
Hi @adminSxs, thank you for filing this issue! It looks like you're trying to query all documents with `_id` values contained in the `doc_ids` array; you may want to use the [`$in`](https://www.mongodb.com/docs/manual/reference/operator/query/in/#mongodb-query-op.-in) query operator for this purpose. For further questions about using the update operation I'd recommend posting on the [MongoDB Community Forum](https://www.mongodb.com/community/forums/c/data/6). Feel free to let me know if you have any questions about using the Rust driver!
