### ISSUE TITLE
Cannot fetch data using find and find_one

### ISSUE THREAD

**Issue by hirohido** [mongodb/mongo-rust-driver#723]
## Versions/Environment
1. Rust Version : rustc 1.62.1
2. MacOS
3. Mongodb = 2.3.0 bson = 2.4.0
4. using mongodb serverless cloud

## Describe the bug
i cannot read read database data using find or find_one. i get an error 

`let mut cursor = collection.find(None, None).await.expect("error occured");
            while let Some(doc) = cursor.try_next().await.unwrap() {
                println!("{:?}", doc)
            }
`

i get an error that says:
BsonDeserialization(DeserializationError { message: "invalid type: map, expected a string" })

**Comment by patrickfreed** [comment]
Hi @hirohido, sorry for the late response!

This error means that the data stored in your database doesn't match the model you're attempting to deserialize to. In this case, the data contains a map (i.e. a document), but your model is expecting a string.

Can you share the struct definition of the type you're deserializing to? Also, could you perform the same query using a `Collection<Document>`, print out the document, and then attempt to deserialize it to that type? This would help give us a better idea of where deserialization is going wrong.
