### ISSUE TITLE
mongodb::bson::DateTime not impl Default trait

### ISSUE THREAD

**Issue by iuyhnbv2048** [mongodb/mongo-rust-driver#749]
## Versions/Environment
1. What version of Rust are you using?  rustc 1.63.0 (4b91a6ea7 2022-08-08)
2. What operating system are you using? macOs Monterey
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) https://github.com/rust-lang/crates.io-index#mongodb@2.3.0 & https://github.com/rust-lang/crates.io-index#bson@2.4.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 6.0
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? standalone

## Describe the bug

when I use `mongodb::bson::DateTime` with [async-graphql](https://github.com/async-graphql/async-graphql) InputObject derive, it says that "the trait `Default` is not implemented for `mongodb::bson::DateTime`".
The doc is [here](https://async-graphql.github.io/async-graphql/en/define_simple_object.html).

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
* Do you have any particular output that demonstrates this problem?
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
* If you know how to reproduce this bug, please include a code snippet here:
```
#[derive(SimpleObject, InputObject, Serialize, Deserialize, Clone, Debug)]
#[graphql(input_name = "UserInput")]
#[graphql(complex)]
pub struct User {
    #[graphql(name = "_id")]
    #[graphql(skip_input)]
    pub _id: ObjectId,
    pub email: String,
    #[graphql(skip_input)]
    pub created_at: DateTime,
}
```
I use vscode with rust-analyzer，and the vscode shows the problem I mentioned above.

![a](https://user-images.githubusercontent.com/52618091/191728025-af348cef-e611-478b-903b-2576a4eb6a44.png)

**Comment by decatur** [comment]
Isn't it more a feature you are requesting?
What would be a **useful default value** for `bson::DateTime`?
Have you tried the attribute `#[graphql(default_with = "my_default()")]` on the `create_at` field, with `my_default` returning
an acceptable value such as `bson::DateTime::now()`?

**Comment by patrickfreed** [comment]
Hi @iuyhnbv2048, thanks for filing this issue.

We discussed this as a team and feel that there wouldn't be a single default value for `DateTime` that would unambiguously make sense. Some might say that `DateTime::now` could be the default, others might suggest that the Unix epoch would be.

Instead, we suggest you adopt a solution  along the lines of what @decatur has laid out by providing a default value that works for your use case.

Thanks again, and let us know if you have any further questions!
