### ISSUE TITLE
`find_one_and_update` hangs in a `async_global_executor::block_on` callback

### ISSUE THREAD

**Issue by Ks89** [mongodb/mongo-rust-driver#750]
## Versions/Environment
1. What version of Rust are you using? `rustc 1.62.1 (e092d0b6b 2022-07-16) and cargo 1.62.1 (a748cf5a3 2022-06-08)`
3. What operating system are you using? `MacOS 12.6 (21G115) on a Macbook Pro 2016 Intel`
4. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) `mongodb 2.3.0 and bson 2.4.0`
5. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`)  `official mongo:6 container from dockerhub`
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? 
```
# everything default from the mongo:6 docker container
docker pull mongo:6
docker run -d --name mongodb -v ~/mongodb:/data/db -p 27017:27017 mongo:6
```

## Describe the bug

When I execute `find_one_and_update` many times inside a `async_global_executor::block_on(async {})` it hangs after some operations. In my tests, it is hanging after 31 operations. Check [this example](https://github.com/Ks89/rust-mongodriver-problem/blob/05b800ed9f02c8f36f78e7e17cda8bffa140258f/src/main.rs#L46).

```
...
Writing i = 31
update success SensorDocument { _id: ObjectId("63290618c9760c6a80d4b034"), uuid: "4cbf8674-6f37-402b-8c35-a76c0f8965ca", mac: "60:55:F9:DF:F8:92", name: "temperature", manufacturer: "temperature", model: "temperature", profileOwnerId: "620d710e4e8fe8f3394084bc", apiToken: "473a4861-632b-4915-b01e-cf1d418966c6", createdAt: DateTime(OffsetDateTime { local_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 263 }, time: Time { hour: 0, minute: 15, second: 20, nanosecond: 351000000 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }), modifiedAt: DateTime(OffsetDateTime { local_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 268 }, time: Time { hour: 11, minute: 36, second: 43, nanosecond: 870000000 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }), value: 10.0 }
Writing i = 32

```

Extracting `find_one_and_update` from the `async_global_executor::block_on` to the `main()`, everything works as expected.

```
...
Writing i = 999
update success SensorDocument { _id: ObjectId("63290618c9760c6a80d4b034"), uuid: "4cbf8674-6f37-402b-8c35-a76c0f8965ca", mac: "60:55:F9:DF:F8:92", name: "temperature", manufacturer: "temperature", model: "temperature", profileOwnerId: "620d710e4e8fe8f3394084bc", apiToken: "473a4861-632b-4915-b01e-cf1d418966c6", createdAt: DateTime(OffsetDateTime { local_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 263 }, time: Time { hour: 0, minute: 15, second: 20, nanosecond: 351000000 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }), modifiedAt: DateTime(OffsetDateTime { local_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 268 }, time: Time { hour: 11, minute: 40, second: 49, nanosecond: 804000000 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }), value: 10.0 }
```

Feel free to ask logs or other stuff because I can reproduce this issue without problems.

**To Reproduce**
1. create a `testdb` db with a `testdb` collection
2. import this document:
```
[{
  "_id": {
    "$oid": "63290618c9760c6a80d4b034"
  },
  "mac": "60:55:F9:DF:F8:92",
  "uuid": "4cbf8674-6f37-402b-8c35-a76c0f8965ca",
  "name": "temperature",
  "manufacturer": "temperature",
  "model": "temperature",
  "profileOwnerId": "620d710e4e8fe8f3394084bc",
  "apiToken": "473a4861-632b-4915-b01e-cf1d418966c6",
  "value": 10,
  "createdAt": {
    "$date": {
      "$numberLong": "1663632920351"
    }
  },
  "modifiedAt": {
    "$date": {
      "$numberLong": "1664101037234"
    }
  }
}]
```
3. clone this repo https://github.com/Ks89/rust-mongodriver-problem
4. run `cargo run`

**Comment by abr-egn** [comment]
Hi!  Thank you for putting together a repro repo - that's very helpful.

It looks like you're spinning up a Tokio executor via the `#[tokio::main]` annotation, and then actually running the body on a different executor via `async_global_executor`.  The Rust driver only supports the tokio and async-std executors - if you remove the use of `async_global_executor` and shift the code to be directly in the body of `main` it should work fine.

**Comment by Ks89** [comment]
Thank you for the explanation. Removing `async_global_executor` everything works as expected
