### ISSUE TITLE
How to find out the path at which a deserialization error occurred.

### ISSUE THREAD

**Issue by unshakable-horse** [mongodb/mongo-rust-driver#775]
## Versions/Environment
1. rust 1.65
2. Mac OS
3. mongodb 2.3.1

When I use "findOne" to recall data from mongo, sometimes my struct definitions may not match, but I can't tell exactly which field is at fault. I only get an icy error " message: "invalid type: sequence, expected a string" ".

**Comment by abr-egn** [comment]
In these situations, you can use the [serde_path_to_error](https://crates.io/crates/serde_path_to_error) crate - for debugging, you'll need to use `Document` as the collection type and construct the deserializer manually from the returned document.

**Comment by unshakable-horse** [comment]
thanks

**Comment by clarkmcc** [comment]
Any chance this could be included out-of-the-box, possibly behind a feature flag or something? Having to rewrite a bunch of deserialization code every time there's a deserialization error is a painful developer experience.

**Comment by isabelatkinson** [comment]
Hey @clarkmcc, RUST-1874 tracks using `serde_path_to_error` internally for deserialization. Feel free to follow that ticket for more updates! It is not currently prioritized, but I marked it for future consideration as this seems to be a common pain point.

**Comment by clarkmcc** [comment]
@isabelatkinson Thanks for the update. Would it be easier to prioritize reviewing a PR for something like this? I may be able to dedicate some cycles, but would hate to take the time if it wouldn't be considered.
