### ISSUE TITLE
Missing: creating array of documents does not create the _id 

### ISSUE THREAD

**Issue by maxidev** [mongodb/mongo-rust-driver#779]
When creating an array of documents given a defined struct, the internal documents of said array does not have the automatic generated _id that we see in other drivers/languages.

Query:
```
  let newDoc = SomeStruct {
    field: vec!(
    mongodb::bson::to_document(&data)
  ),
  };
  let vault = col.insert_one(newDoc, None).await;
```

The model/struct:

```
pub struct Vault {
  pub field: Vec<mongodb::bson::Document>,
}
```
Tried both with document also just using the struct as Vec in the field.

The _id field is just missing, no error whatsoever, but I need that _id for my application.

Tried both using to_document from bson but also directly inject as the struct type.

## Versions/Environment
1. What version of Rust are you using? 
cargo 1.63.0 (fd9c4297c 2022-07-01)
2. What operating system are you using?
OS: Manjaro Linux x86_64
4. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
(https://github.com/rust-lang/crates.io-index#mongodb@2.3.0)
5. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
MongoDB 4.4.11 Community
6. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
replica set

**Comment by isabelatkinson** [comment]
Hi @maxidev, an `_id` field is only generated for the top-level documents being inserted into your collection. For instance, the document inserted into your collection from your example will look something like this:

```
{
    "_id": <driver-generated ObjectId value>
    "field": <the documents contained in the field value of the struct>
}
```

You can inspect the value of this `_id` via the [`inserted_id`](https://docs.rs/mongodb/latest/mongodb/results/struct.InsertOneResult.html#structfield.inserted_id) field of the `InsertOneResult` returned by `insert_one`.

The driver will not recurse through your data to append `_id` fields to any sub-documents contained within documents/arrays. If you'd like to generate a unique identifier for sub-documents, I'd recommend doing so manually with the [`ObjectId::new`](https://docs.rs/bson/latest/bson/oid/struct.ObjectId.html#method.new) function.

**Comment by maxidev** [comment]
@isabelatkinson got it! thanks for the reply, I guess I was just used to the Mongoose (nodejs ORM for Mongo) that does that automatically so I was looking for the same feature here. But has you suggesed solved it by doing exactly that.
Thanks again,
Maxi.
