### ISSUE TITLE
Can't filter by ObjectID

### ISSUE THREAD

**Issue by elibroftw** [mongodb/mongo-rust-driver#800]
It is very convenient that the examples provided under usage never filter by _id. Why is it so difficult? It feels like I'm the only one using MongoDB in Rust even though there's 1.2k stars.

Please let me know which one of these is the right answer. 

```rs
let id = "63b4d581231527b4896f36e6";
let oid = ObjectId::parse_str(&id)?;
let posts_coll = db.app_db().collection::<BlogPost>("posts");
posts_coll.find_one(doc!{"_id": &id}, None).await.unwrap()  // 404
posts_coll.find_one(doc!{"_id": oid}, None).await.unwrap()  // Serialize error
posts_coll.find_one(doc!{"_id": {"$oid": &id}}, None).await.unwrap()  // unknown operator $set
posts_coll.find_one(doc!{"_id": oid.to_string()}, None).await.unwrap()  // 404
```

You might have realized this is too intuitive for developers. Only an unintuitive solutions should work!

Let's create an entirely new struct just for the sake of filtering by id! What an ingenious solution! Nobel prize status.

```rs

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Id{
    pub _id: ObjectId
}

posts_coll.find_one(bson::to_document(&Id{_id: oid}).unwrap(), None).await.unwrap()
```
Nahhhhh same errors

thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: BsonDeserialization(DeserializationError { message: "invalid type: map, expected a string" }), labels: {}, wire_version: None, source: None }', src\blog.rs:59:86

Maybe we need to change the type of the collection to Document? Nah that doesn't work either!

Full code

```rs
#[get("/posts/<id>")]
async fn blog_post(id: String, db: Connection<MainDatabase>) -> Result<Template, Status> {
    let posts_coll = db.app_db().collection::<Document>("posts");
    let oid = ObjectId::parse_str(&id).map_err(|_e| Status::InternalServerError)?;
    print!("{id}");
    match posts_coll.find_one(doc!{"_id": &id}, None).await.unwrap() {
        Some(post) => Ok(Template::render("blog/post", context! {post})),
        _ => Err(Status::NotFound)
    }
}
```

posts collection

```
{
  "_id": {
    "$oid": "63b4d581231527b4896f36e6"
  },
  "title": "First Post!!!",
  "content": "Hey there, this is some rad content",
  "published": {
    "$date": "2023-01-04T01:25:21.194Z"
  }
}
```
63b4d581231527b4896f36e6

posts_coll.find_one(doc!{"title": "First Post!!!"}, None).await.unwrap()

works fine

**Comment by kmahar** [comment]
Hi @elibroftw. 

How did you insert the document, and how are you printing it out in the output you show?

I was able to run the following code with no issue so I suspect you must have inserted the document differently than I did:

```rust 
#[derive(Serialize, Deserialize, Debug)]
struct BlogPost {
    _id: ObjectId,
}

#[tokio::main]
async fn main() {
    let mongo_uri = env::var("MONGODB_URI").unwrap_or_default();
    let client_options = ClientOptions::parse(mongo_uri).await.unwrap();
    let client = Client::with_options(client_options).unwrap();
    let db = client.database("test");
    db.drop(None).await.unwrap(); // clear out existing data

    let id = "63b4d581231527b4896f36e6";
    let oid = ObjectId::parse_str(&id).unwrap();
    let posts_coll = db.collection::<BlogPost>("posts");

    posts_coll.insert_one(BlogPost { _id: oid.clone() }, None).await.unwrap();

    match posts_coll.find_one(doc! { "_id": oid }, None).await {
        Ok(v) => {
            match v {
                Some(post) => { println!("found post: {:?}", post) },
                None => println!("no matching post found"),
            }
        },
        Err(e) => {
            println!("error finding post: {}", e);
        }
    }
}
```

This gave me the following output:
```
found post: BlogPost { _id: ObjectId("63b4d581231527b4896f36e6") }
```

Additionally, is it possible any other code is being executed on the path where you are getting the errors you show? As far as I can tell, the only way to get an error back from the server containing "unknown operator $set" is to include "$set" in a query. The driver would never add that itself, so that error output is likely from somewhere else in your program.

**Comment by elibroftw** [comment]
Yeah it must've been some sort of insert issue because I had to add in the _id field manually and I must've changed the struct field between developing. Works now so thanks.
