### ISSUE TITLE
How to close the connection manually

### ISSUE THREAD

**Issue by JaydenWooDotCom** [mongodb/mongo-rust-driver#804]
How can I close the connection manually before my program exit?

**Comment by abr-egn** [comment]
You can initiate the connection close by dropping the `Client` and any `Database` or `Collection` derived from it.  Note that some background cleanup work will continue after the drop point; if you need stronger timing you can listen for a [PoolClosedEvent](https://docs.rs/mongodb/2.3.1/mongodb/event/cmap/struct.PoolClosedEvent.html).
