### ISSUE TITLE
Question: Best way to share one client instance across multiple structs(repository pattern)

### ISSUE THREAD

**Issue by LukasDeco** [mongodb/mongo-rust-driver#809]
Hello!

I'm trying to use a type of repository pattern which is coupled to mongodb for now. I want various repository structs that implement a repository trait and contain a client property pointing to one isntance of the mongodb client. I am new to Rust and so I am strugglign with this for sure. Here's my repository trait:

```
use std::borrow::Borrow;

use async_trait::async_trait;
use mongodb::{
    bson::Document, error::Error, options::FindOneOptions, results::InsertOneResult, Client,
};
use serde::{de::DeserializeOwned, Serialize};

#[async_trait]
pub trait Repository<'a> {
    fn with_client(client: &'a Client) -> Self;
    async fn find_one<'b, T: DeserializeOwned + Sync + Send + Unpin>(
        &self,
        filter: Document,
        find_one_options: FindOneOptions,
    ) -> Result<Option<T>, Error>;

    async fn insert_one<'b, T: DeserializeOwned + Sync + Send + Unpin + Serialize>(
        &self,
        new_document: impl Borrow<T> + Send + Sync,
    ) -> Result<InsertOneResult, Error>;
}
```

I'm hoping to get recommendations on how I could possibly improve this structure. Right now I'm having trouble in my main function sharing the one instance of the Client across multiple Futures. My app will have both http listeners and mongodb change stream listeners, so I am trying to return with a join_all at the end of my main function like this:

```
async fn main() {
    let mongo_uri = env::var("MONGO_URI").unwrap_or_default();

    // Parse your connection string into an options struct
    let client_options = ClientOptions::parse(mongo_uri).await.unwrap();

    // Get a handle to the cluster
    let client_result = Client::with_options(client_options);
    let client = client_result.unwrap();
    // Ping the server to see if you can connect to the cluster
    println!("Connected successfully.");

    // Wrap the code that uses the `client` variable in a new async block
    let a_repository = ARepository::with_client(&client);
    let b_repository = BRepository::with_client(&client);

    let business_logic_struct=  BusinessLogicStruct::new(
        &a_repository ,
        &b_repository ,
    );

    futures::future::join(
        events::notifications::new_insert_change_stream(&mut &client, &business_logic_struct),
        start_server(&business_logic_struct), // running into borrow issues here
    )
    .await;
}
```

Again, I am very new to rust. I really appreciate any advice you can give. Thanks!

**Comment by kmahar** [comment]
Hi @LukasDeco, rather than passing the `Client` around by reference you can `clone` it and pass it that way to avoid the borrow issues you're noting. The client wraps all of its inner state in an `Arc` so it will automatically share all the inner state throughout your app even if you `clone` it. This should remove the need for you to handle the lifetime and borrowing issues.

**Comment by LukasDeco** [comment]
Hi @kmahar thank you for providing the info. Thanks that makes things a lot simpler, and I went ahead and implemented this. Works like charm!
