### ISSUE TITLE
MongoDB Rust Driver + Actix Web on Apple Silicon

### ISSUE THREAD

**Issue by santiagomed** [mongodb/mongo-rust-driver#817]
## Versions/Environment
1. What version of Rust are you using? 
1.66.0
2. What operating system are you using?
Apple Silicon
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
https://github.com/rust-lang/crates.io-index#mongodb@2.3.1
https://github.com/rust-lang/crates.io-index#bson@2.5.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
5.0.14
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
Cluster M0 Sandbox (General), Shared Cluster MongoDB Atlas

## Describe the bug

I am using the MongoDB Rust driver and Actix Web on my Apple M1 Max and it doesn't seem to be working properly. Whenever I make a query or db manipulation function, the server hangs for some time and then it panics.

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
**Expected behavior** Document should be successfully inserted and the database should reflect this change.
**Actually happening** It hangs for around 30s when I make the request, and then it prints out an error.
* Do you have any particular output that demonstrates this problem?
After making the request to create the user it hangs for like 30s and the server outputs the following
```
thread 'actix-rt|system:0|arbiter:2' panicked at 'Failed to insert document', server/src/repository/db.rs:81:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
It DOES work on my desktop PC so I am wondering if it has something to do with running the server on Apple Silicon.
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? 
Only when on my M1 mac
* Are there multiple ways of triggering this bug (perhaps more than one function produces a crash)?
Any function that queries/manipulates the Mongo database. I have this issue with `update_one` as well.
* If you know how to reproduce this bug, please include a code snippet here:
```
let user = self.user_collection
                               .insert_one(new_doc, None)
                               .await
                               .ok()
                               .expect("Failed to insert document");
Ok(user)
```
On an Apple Silicon machine

**To Reproduce**
1. Make a query to a MongoDB database
2. Run the query
3. Bug occurs.

**Comment by abr-egn** [comment]
Hi!  Unfortunately, by using `ok()` to convert the error to an `Option`, information about the specific error is lost - can you run again without the `.ok()` in the call chain and update here with the error that gives?

**Comment by santiagomed** [comment]
Hey @abr-egn thanks for the quick response. I figured it out: It wasn't an issue with my Mac, but with the network permissions on MongoDB Atlas! It felt like it was a Mac issue because I only use it when I'm not home, so I was accessing MongoDB Atlas from a different network, and thus access was restricted. All fixed now!

That said, do you recommend not using `.ok()` for situations like this anyways?

**Comment by abr-egn** [comment]
Ah, glad it's fixed 🙂 

In general, yeah, I'd recommend not using `.ok()` for this kind of thing.  Ideally you'd be able to propagate the errors but if that's not possible `.expect` directly on the `Result` will give much more useful error messages.
