### ISSUE TITLE
authMechanism=DEFAULT is not working

### ISSUE THREAD

**Issue by devSupport-India** [mongodb/mongo-rust-driver#834]
## Versions/Environment
1. What version of Rust are you using? 1.67.1
2. What operating system are you using? Windows 11
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`) mongodb@2.3.1 and bson@2.5.0
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 6.0.3
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? replica set

## Describe the bug
Getting error :- 
```
 Error { kind: InvalidArgument { message: "invalid mechanism string: DEFAULT" }, labels: {}, wire_version: None, source: None }', 
```

URI:
```
 mongodb://user:password@server1.ltd:27017,server2.ltd:27017,server3.ltd:27017/?authMechanism=DEFAULT&authSource=admin&replicaSet=test
```
The above URI is working fine if I remove authMechanism parameter

**Comment by isabelatkinson** [comment]
Hi @devSupport-India, thanks for filing this issue! "DEFAULT" is not a supported value for the `authMechanism` parameter of the connection string. If an `authMechanism` is not provided in the connection string, a default is chosen by the logic described [here](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#defaults).
