### ISSUE TITLE
Field name safety

### ISSUE THREAD

**Issue by MiniaczQ** [mongodb/mongo-rust-driver#839]
Hello, I've been recently switching from ASP.NET to Rust while working with MongoDB.

I've been enjoying it so far, but I couldn't find a convention for validating struct field names in documents, especially `UpdateModifications`. Is there a way to check that at compile time?

If not, the closest thing I'm aware of to make this possible would be [`Lens` derive macro](https://docs.rs/druid/latest/druid/derive.Lens.html) which generates string constants for each field.

EDIT:
Small example to give a better understanding:
```rust
#[derive(Serialize, Deserialize)]
struct Foo {
  #[serde(rename = "_id")]
  id: Uuid,
  bar: u32,
  // [...]
}
```
```rust
client.find_one_and_update(
        doc! {"_id": user_id}, // In this case we need `serde`'s redefined fieldname
        doc! {"$set": {"bar": 5}}, // We need `bar` as a string here, no connection to the struct at all
        None,
).await.unwrap();
```

**Comment by oneslash** [comment]
Okay, here is how I fixed it:

```
$ cargo install cargo-cache
$ cargo cache -a
```

**Comment by MiniaczQ** [comment]
Small update, I was suggested this article which describes a much cleaner and more thought through solution:
http://www.cmyr.net/blog/keypaths.html
The only thing missing is serdename override.

**Comment by abr-egn** [comment]
Unfortunately, as you've largely found, this isn't something where it's possible to have a robust solution - a custom `Serialize` implementation can do whatever it wants with the contents of the struct, including writing out completely different fields or none at all.  This isn't specific to the Rust MongoDB driver or Bson implementation, it's more of a general shortcoming of the approach taken by serde.
