### ISSUE TITLE
mongodb::options::ClientOptions behaving differently when "tokio-sync" is enabled

### ISSUE THREAD

**Issue by c-thiel** [mongodb/mongo-rust-driver#845]
## Versions/Environment
1. What version of Rust are you using? 
1.68
3. What operating system are you using?
Ubuntu
5. What versions of the driver and its dependencies are you using? 
mongodb@2.4.0

## Describe the bug
When using the "tokio-sync" feature, `mongodb::options::ClientOptions::parse("mongodb://localhost:27017")` returns a Result. When the feature is disabled, a future is returned.

The ClientOptions in `mongodb::options` should behave consistently idependant of the feature. I would expect a sync version in `mongodb::sync::options`.

**Comment by abr-egn** [comment]
Hi!  Sorry for the delay.

You're right, that's not a good situation.  This is an artifact of when the async and sync APIs were mutually exclusive; we missed this when removing that restriction.  Unfortunately, at this point changing `ClientOptions::parse` to always be async would be a breaking change for users of the sync API.  Our plan here is to add a `ClientOptions::parse_async` method that's always async so users enabling both APIs still have access to the async version; fixing this in a cleaner way will go on the list for breaking changes in 3.0 (which won't be soon).

Will that approach address your situation?

**Comment by abr-egn** [comment]
I've filed https://jira.mongodb.org/browse/RUST-1632 and https://jira.mongodb.org/browse/RUST-1633 to track the immediate mitigation and long-term cleanup respective.

**Comment by abr-egn** [comment]
`parse_async` has been merged and will go out next week with 2.5.0.
