### ISSUE TITLE
how to close change_stream?

### ISSUE THREAD

**Issue by laik** [mongodb/mongo-rust-driver#847]
## Versions/Environment
1. What version of Rust are you using?    
```
   rustc 1.70.0-nightly (db0cbc48d 2023-03-26)
```
2. What operating system are you using?
```
  macos
```
3. What versions of the driver and its dependencies are you using? (Run 
`cargo pkgid mongodb` & `cargo pkgid bson`)
https://github.com/rust-lang/crates.io-index#mongodb@2.3.0

4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
```
 5.0.6
```
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?
```
replica set
```

## Describe the bug

```
^Cthread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) })', /Users/dxp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mongodb-2.3.0/src/cmap/connection_requester.rs:37:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/result.rs:1752:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/result.rs:1092:23
   4: mongodb::cmap::connection_requester::ConnectionRequester::request::{{closure}}
             at /Users/dxp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mongodb-2.3.0/src/cmap/connection_requester.rs:37:9
   5: mongodb::cmap::ConnectionPool::check_out::{{closure}}
             at /Users/dxp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mongodb-2.3.0/src/cmap/mod.rs:134:59
   6: mongodb::client::executor::get_connection::{{closure}}
```

**BE SPECIFIC**:

```
When using the tokio upper layer to call changestream to close, the above-mentioned bug occurs in changestream. How to gracefully close this running changestream?
```

** when **
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/11013552/228725656-14798064-2af1-4ecf-aa7d-f6225a2dcf11.png">

**Comment by isabelatkinson** [comment]
Hi @laik, this issue you're experiencing is likely related to a known problem in the driver that causes tasks to panic while the async runtime shuts down. You can take a look at RUST-1099 for more details on this. We plan to address this problem in the future, but as a workaround I'd recommend dropping the change stream manually prior to the runtime shutting down.
