### ISSUE TITLE
Bson DateTime not deserialize properly

### ISSUE THREAD

**Issue by tonyhart7** [mongodb/mongo-rust-driver#873]
ok it seriliaze works but when deserialize it still output bson::datetime 

I want deserialize automatically to datetime<utc>

~~~
pub struct Clock {
    #[serde(with = "chrono_datetime_as_bson_datetime")]
    pub clock_time: chrono::DateTime<chrono::Utc>,
    pub event_type: ClockEventType,
    pub status: ClockStatus,
}

~~~

~~~
"clock_time": {
                "$date": {
                    "$numberLong": "1683721549191"
                }
            },
~~~

**Comment by tonyhart7** [comment]
@abr-egn sorry to bother you again

**Comment by tonyhart7** [comment]
nah chatgpt generate it for me
I must write my own deseriliaze from bson::datetime 

You can close it if its expected issue, below is example code


~~~
use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Deserializer, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum ClockStatus {
    Late,
    Present,
    Leave,
    Sick,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Location {
    pub latitude: f64,
    pub longitude: f64,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum ClockEventType {
    ClockIn,
    ClockOut,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Clock {
    pub corpo_uid: String,
    pub employee_uid: String,
    #[serde(deserialize_with = "deserialize_datetime_utc")]
    pub clock_time: DateTime<Utc>,
    pub event_type: ClockEventType,
    pub status: ClockStatus,
    pub notes: Option<String>,
    pub location: Option<Location>,
    pub break_duration: Option<i64>,
    pub total_duration: Option<i64>,
}

fn deserialize_datetime_utc<'de, D>(deserializer: D) -> Result<DateTime<Utc>, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct ClockTime {
        #[serde(rename = "$date")]
        date: Date,
    }

    #[derive(Deserialize)]
    struct Date {
        #[serde(rename = "$numberLong")]
        number_long: String,
    }

    let clock_time: ClockTime = Deserialize::deserialize(deserializer)?;
    let timestamp: i64 = clock_time.date.number_long.parse().map_err(serde::de::Error::custom)?;
    Ok(DateTime::<Utc>::from_utc({
        let secs = timestamp / 1000;
        let datetime = NaiveDateTime::from_timestamp_opt(secs, 0);
        datetime.expect("invalid or out-of-range datetime")
    }, Utc))
}

// Example usage
fn main() {
    let json = r##"
    {
        "corpo_uid": "2PK7a6Hq1ujoD4ujYeT3pLxUU9k",
        "employee_uid": "2PK8WXK9VKVqYh5VqXkr9tR8th1",
        "clock_time": {
            "$date": {
                "$numberLong": "1683723639539"
            }
        },
        "event_type": "ClockIn",
        "status": "Late",
        "notes": "ini adalah note",
        "location": {
            "latitude": 40.712776,
            "longitude": -74.005974
        },
        "break_duration": null,
        "total_duration": null
    }
    "##;

    let clock: Clock = serde_json::from_str(json).unwrap();
    println!("{:?}", clock);
}

~~~

**Comment by tonyhart7** [comment]
> Can you explain a little more about the problem you encountered with your first snippet? I don't understand what you were looking for vs what actually happened.
> 
> As a side note, I wouldn't recommend chatgpt for generating code using the `bson` or `mongodb` crates - on top of the normal accuracy problems its training corpus is years out of date and our libraries have changed quite a bit since then.

![image](https://github.com/mongodb/mongo-rust-driver/assets/42036827/ac0737f4-92e5-448a-b4c9-8aedb0eaaccf)

bson::datetime not deseriliaze as datetime

**Comment by tonyhart7** [comment]
this is my own helper 
~~~
pub mod bson_date_helper {

    use chrono::{DateTime as ChronoDateTime, NaiveDateTime, Utc};
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use std::result::Result;

    /// Deserializes a [`chrono::DateTime`] from a [`bson::DateTime`].
    #[cfg_attr(docsrs, doc(cfg(feature = "chrono-0_4")))]
    pub fn deserialize<'de, D>(deserializer: D) -> Result<chrono::DateTime<Utc>, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct ClockTime {
            #[serde(rename = "$date")]
            date: Date,
        }

        #[derive(Deserialize)]
        struct Date {
            #[serde(rename = "$numberLong")]
            number_long: String,
        }

        let clock_time: ClockTime = Deserialize::deserialize(deserializer)?;
        let timestamp: i64 = clock_time
            .date
            .number_long
            .parse()
            .map_err(serde::de::Error::custom)?;
        Ok(ChronoDateTime::<Utc>::from_utc(
            {
                let secs = timestamp / 1000;
                let datetime = NaiveDateTime::from_timestamp_opt(secs, 0);
                datetime.expect("invalid or out-of-range datetime")
            },
            Utc,
        ))
    }

    /// Serializes a [`bson::DateTime`] as a [`chrono::DateTime`].
    #[cfg_attr(docsrs, doc(cfg(feature = "chrono-0_4")))]
    pub fn serialize<S: Serializer>(
        val: &chrono::DateTime<Utc>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        let datetime = bson::DateTime::from_chrono(val.to_owned());
        datetime.serialize(serializer)
    }
}
~~~

and its just store it back to datetime<utc> in database silly me
I feel bambloozed, can we deseriliaze it to datetime without changing bson::datetime in database ?

**Comment by abr-egn** [comment]
I'm sorry but I'm still a bit lost trying to understand what you're looking for.

What format is the field in your database?  BSON DateTime (`{"$date": {"$numberLong": "<millis>"}}`), date string (`"1996-12-19T16:39:57-08:00"`), something else?

What data type would you like to use in your Rust code for this field?  `bson::DateTime`, `chrono::DateTime`, something else?

**Comment by tonyhart7** [comment]
> I'm sorry but I'm still a bit lost trying to understand what you're looking for.
> 
> What format is the field in your database? BSON DateTime (`{"$date": {"$numberLong": "<millis>"}}`), date string (`"1996-12-19T16:39:57-08:00"`), something else?
> 
> What data type would you like to use in your Rust code for this field? `bson::DateTime`, `chrono::DateTime`, something else?



this is in database

~~~
{
  "corpo_uid": "2PK7a6Hq1ujoD4ujYeT3pLxUU9k",
  "employee_uid": "2PK8WXK9VKVqYh5VqXkr9tR8th1",
  "clock_time": {
                "$date": {
                    "$numberLong": "1683729817505"
                }
            },
  "event_type": "ClockIn",
  "status": "Late",
  "notes": "ini adalah note",
  "location": {
    "latitude": 40.712776,
    "longitude": -74.005974
  },
  "break_duration": null,
  "total_duration": null
}
~~~

this is rust model 


~~~
pub struct Clock {
    pub corpo_uid: String,
    pub employee_uid: String,
    #[serde(with = "chrono_datetime_as_bson_datetime")]
    pub clock_time: chrono::DateTime<chrono::Utc>,
    pub event_type: ClockEventType,
    pub status: ClockStatus,
    pub notes: Option<String>,
    pub location: Option<Location>,
    pub break_duration: Option<i64>,
    pub total_duration: Option<i64>,
}
~~~

I can query date range easily back and fort in my rust its great, its works
but when I fetch data it came back as bson::datetime 

like in here

![image](https://github.com/mongodb/mongo-rust-driver/assets/42036827/54580f4d-3008-4eb0-8a5c-e46254869854)

**Comment by abr-egn** [comment]
I'm glad the Rust code works! 🙂 

For MongoDB to be able to query dates with operators like range, the field needs to be stored in the format MongoDB understands, which is the one you're seeing returned above - I'm afraid there isn't much of a way around that.  For browsing, you can convert the timestamp in the date (`"1683729817505"`) into a human-readable date by using a unix timestamp converter like https://unixtime.org/.

**Comment by tonyhart7** [comment]
> I'm glad the Rust code works! 🙂
> 
> For MongoDB to be able to query dates with operators like range, the field needs to be stored in the format MongoDB understands, which is the one you're seeing returned above - I'm afraid there isn't much of a way around that. For browsing, you can convert the timestamp in the date (`"1683729817505"`) into a human-readable date by using a unix timestamp converter like https://unixtime.org/.

Yeah the problem is I cant make wrapper in front end because it contain '$' symbol, it uses for variable reference
