### ISSUE TITLE
No bulk write function

### ISSUE THREAD

**Issue by ktjd123** [mongodb/mongo-rust-driver#890]
Hi,

Is there planned release date for bulkWrite function expose?

Saw it will be exposed at end of 2022 but seems no update.

Thank you.

**Comment by danielsan** [comment]
I should have researched this before migrating a nodejs app to Rust.
The app performs several updateOne operations per bulk request and doing that one by one over the wire is much slower.

How can we help this feature get prioritized/done?

**Comment by isabelatkinson** [comment]
@danielsan the bulk write feature is nearing completion and should be released within the coming weeks. Please note that the actual server command that it uses is introduced in server version 8.0, which is only available as a [release candidate](https://www.mongodb.com/zh-cn/docs/upcoming/release-notes/8.0/) right now.

In the meantime, you can use the [`run_command`](https://docs.rs/mongodb/latest/mongodb/struct.Database.html#method.run_command) method to send an [`update`](https://www.mongodb.com/docs/manual/reference/command/update/) operation with multiple updates in the `updates` array.

**Comment by isabelatkinson** [comment]
Bulk write will be released in the upcoming 3.0.0-beta release, going to close this out.

**Comment by ShaunSHamilton** [comment]
@isabelatkinson 
> Please note that the actual server command that it uses is introduced in server version 8.0, which is only available as a [release candidate](https://www.mongodb.com/zh-cn/docs/upcoming/release-notes/8.0/) right now.

Would you mind clarifying if v8 is needed for bulk writes to the same collection as well:
> Starting in MongoDB 8.0, you can use the new [bulkWrite](https://www.mongodb.com/zh-cn/docs/upcoming/reference/command/bulkWrite/#mongodb-dbcommand-dbcmd.bulkWrite) command to perform many insert, update, and delete operations on multiple collections in one request. The existing [db.collection.bulkWrite()](https://www.mongodb.com/zh-cn/docs/upcoming/reference/method/db.collection.bulkWrite/#mongodb-method-db.collection.bulkWrite) method only allows you to modify one collection in one request.

Specifically, I see the [mongodb docs.rs](https://docs.rs/mongodb/3.0.0/mongodb/index.html) only mention a requirement of `3.6+`.

**Comment by isabelatkinson** [comment]
Hey @ShaunSHamilton, 8.0 is required for any kind of bulk write using the `bulk_write` method, regardless of how many namespaces are being written to. The Rust driver does not implement the `db.collection.bulkWrite()` method that the docs you quoted refer to.
