### ISSUE TITLE
Add feature flag for time 0.3 support

### ISSUE THREAD

**Issue by FalkWoldmann** [mongodb/mongo-rust-driver#909]
Hi, 
I've seen that you provide a feature flag with support for chrono 0.4. Would it be possible to add an additional flag for time 0.3? It looks like bson [already supports this](https://github.com/mongodb/bson-rust/blob/b243db19b74745fcf52eacd9e4d34077186186d5/Cargo.toml#L45) as a feature flag.

**Comment by felschr** [comment]
Just to clarify, `mongodb` 2.6 can already be used with `time` by adding `bson` to ones dependencies with the `time-0_3` feature flag.

The `bson-{x}`-style feature flags of `mongodb` just affect the reexported module.
Of course it's desirable that the corresponding flag for `time` will be added eventually.

**Comment by isabelatkinson** [comment]
Hi @FalkWoldmann, thanks for filing this issue! While we do currently have some feature flags in the driver exposing `bson` features, this is a practice we have decided to move away from, and we plan to remove the bson-related feature flags in our next major release. Instead, we suggest users do what @felschr outlined above: add `bson` as its own dependency in your `Cargo.toml` file and toggle whichever feature flags are desired there.
