### ISSUE TITLE
RUST-229 Connection string parser does not support IPv6 addresses

### ISSUE THREAD

**Issue by aqrln** [mongodb/mongo-rust-driver#916]
## Versions/Environment
`mongodb@2.3.0`, `mongodb@2.6.0` and latest from git

## Describe the bug

`ServerAddress::parse` simply splits the hostname and port by `:` character which doesn't work with IPv6 addresses, as it splits in the middle of the address and not after the `]` character.

**To Reproduce**
1. Try to connect with a connection string like `mongodb://root:root@[::1]:27018/tests`
2. The driver returns the following error: `port must be valid 16-bit unsigned integer, instead got:  `

**Comment by isabelatkinson** [comment]
Hi @aqrln, RUST-229 tracks the progress of implementing ipv6 address support. We do not currently have this work on our roadmap, but we would welcome a pull request if this is something you are looking for in the near future.

**Comment by aqrln** [comment]
Got it, thanks for the quick response @isabelatkinson!

**Comment by isabelatkinson** [comment]
Closing this as RUST-229 has been implemented and will be included in the next release.
