### ISSUE TITLE
MongoDB search using UUID returns no results despite matching documents in the collection.

### ISSUE THREAD

**Issue by wkargul** [mongodb/mongo-rust-driver#937]
## Versions/Environment
1. rustc 1.71.1 (eb26296b5 2023-08-03)
2. Windows 11 x64
3.
```toml
[dependencies]
mongodb = { version = "2.6.1", features = ["bson-uuid-1"] }
uuid = "1.4.1"
```
4. MongoDB v3.7
5. Standalone

## Description
I've encountered an issue where a MongoDB search using a UUID as a filter is not returning any results. This is unexpected, as I have documents in the collection with the exact UUID value I'm filtering by.

Here's the code snippet in question:
```rust
#[tokio::main]
async fn main() -> mongodb::error::Result<()> {
    // Connect to MongoDB.
    let client = Client::with_uri_str("mongodb://localhost:27017").await.unwrap();
    let database = client.database("your_database_name");
    let collection = database.collection("your_collection_name");

    // UUID you want to search for.
    let desired_uuid = Uuid::parse_str("936DA01F-9ABD-4D9D-80C7-02AF85C822A8").unwrap();
    let filter = bson::doc! {
        "uuid": desired_uuid
    };

    // Fetch documents that match the filter criteria.
    let mut cursor = collection.find(Some(filter), None).await.unwrap();

    // Iterate over the results of the cursor.
    while let Some(result) = cursor.try_next().await.unwrap() {
        println!("result: {:?}", result);
   };

    Ok(())
}
```

Despite the above code, no results are printed to the console. I've double-checked my collection, and I'm certain that there are documents with the "uuid" field in Binary format that matches the `desired_uuid`.

Is there any known issue regarding filtering with UUID?

**Comment by flpStrri** [comment]
I was facing the same issue and I found that when serializing an `uuid::Uuid` with `serde` it saves at mongoDB a `BinData(0, '4YPQlzAyT6OPrwiKusm2iw==')` but when doing something similar to what you did, @wkargul, it searches with `Binary(0x4, 4YPQlzAyT6OPrwiKusm2iw==)`.

Doubling down on the research I found this at the `bson::uuid` doc: https://docs.rs/bson/latest/bson/uuid/index.html
> The popular [uuid](https://docs.rs/uuid) crate also provides a [UUID type](https://docs.rs/uuid/latest/uuid/struct.Uuid.html), though its serde implementation does not produce or parse subtype 4 binary values. Instead, when serialized with bson::to_bson, it produces as a string, and when serialized with bson::to_vec, it produces a binary value with subtype 0 rather than 4...

And it recommends:
> Because of this, it is highly recommended to use the [crate::Uuid](https://docs.rs/bson/latest/bson/struct.Uuid.html) type when working with BSON instead of the uuid crate’s [Uuid](https://docs.rs/bson/latest/bson/struct.Uuid.html), since [crate::Uuid](https://docs.rs/bson/latest/bson/struct.Uuid.html) correctly produces subtype 4 binary values via either serialization function.

**Comment by wkargul** [comment]
Yo @flpStrri, big thanks for the help – you're a lifesaver! 👍

@abr-egn this can be closed.  My bad for missing it in the `bson::uuid` docs.

**Comment by abr-egn** [comment]
Thanks again @flpStrri !
