### ISSUE TITLE
[docs] Need more info on recommendations for `Collection::count_documents` methods

### ISSUE THREAD

**Issue by cailloumajor** [mongodb/mongo-rust-driver#967]
Hi, in the documentation for the methods [`Collection::count_documents`](https://docs.rs/mongodb/2.7.0/mongodb/struct.Collection.html#method.count_documents) and [`Collection::count_documents_with_session`](https://docs.rs/mongodb/2.7.0/mongodb/struct.Collection.html#method.count_documents_with_session), it is recommended to use another method (`Collection::estimated_document_count`). I didn't find any such recommendation nor explanation for this in https://www.mongodb.com/docs/v7.0/reference/method/db.collection.countDocuments/. Furthermore, these methods do not have the same purpose as the recommended one.

If relevant, I would be happy to make a pull request.

**Comment by isabelatkinson** [comment]
Hey @cailloumajor, you're right that this recommendation does not align with the MongoDB-wide guidance on how to use these methods. We would recommended using `estimatedDocumentCount` when an outdated/incorrect count is tolerated (see [here](https://www.mongodb.com/docs/manual/reference/method/db.collection.estimatedDocumentCount/#behavior) for more info) and `count` when total accuracy is needed. Feel free to make a pull request updating this info if you'd like to!
