### ISSUE TITLE
Connection for too long

### ISSUE THREAD

**Issue by Bylx666** [mongodb/mongo-rust-driver#972]
## Versions/Environment
1. rustc 1.70.0
2. Windows 11 22621.2283
3. both bson and mongo at 2.7.0
4. Mongodb Atlas online server
5. with Atlas default topology

## Describe the bug
Im new with rust, and interested with high performance about rs and mongodb. With official sample, every time I got returned value from "Client::with_uri_str" with waiting over 40 secs.
### Source code
The essential codes are here.
``` rust
use mongodb::Client;
use std::time::Instant;

#[tokio::main]
async fn main() {
    let t = Instant::now();
    println!("start here");
    let _client = Client::with_uri_str("mongodb+srv://adm:myserver@cluster.hkdun.mongodb.net/cluster?retryWrites=true&w=majority").await.unwrap();
    dbg!(t.elapsed());
}
```
### My explores
1. Exluding network problem with nodejs, that connected for under 0.5s.
2. Using sync mongodb lib did not change about 40s.

I tried looking with mongodb and deps, and found the bad source is from `txt_lookup` from `async_resolver` crate, but I'm now unavailable to shoot the trouble. In one database connection, there are two `txt_lookup` calls, for 10secs and 30secs. 

Is it my fault here?

**Comment by abr-egn** [comment]
I believe you're running into the [known issue](https://crates.io/crates/mongodb#windows-dns-note) with the `trust-dns-resolver` crate on Windows, you should be able to mitigate this by specifying an alternate resolver config:
```
let options = ClientOptions::parse_with_resolver_config(
    "mongodb+srv://adm:myserver@cluster.hkdun.mongodb.net/cluster?retryWrites=true&w=majority",
    ResolverConfig::cloudflare(),
)
.await?;
let client = Client::with_options(options)?;
```

**Comment by Bylx666** [comment]
https://github.com/mongodb/mongo-rust-driver/issues/972
