### ISSUE TITLE
Handle WriteError while insert_one

### ISSUE THREAD

**Issue by adrien3d** [mongodb/mongo-rust-driver#982]
During an `insert_one` operation, I want to check the error type to see if it is acceptable or not.
Using the following code:
```rust
let collection = client.database(DB_NAME).collection(users::REPOSITORY_NAME);
match collection.insert_one(user, None).await {
    Ok(_) => Ok(self),
    Err(error) => {
        let e =  *error.kind;
        bail!("seed_user insert error: {}", e);
    }
}
```
I have the following error:
```
Error: seed_user insert error: An error occurred when trying to execute a write operation: WriteError(WriteError { code: 11000, code_name: None, message: "E11000 duplicate key error collection: base-api.users index: email_1 dup key: { email: \"adrien3d@gmail.com\" }", details: None })
```

How can I use the `e` or the `error`, or the `error.kind` to compare it with a `WriteError` or `WriteError.code`?

**Comment by isabelatkinson** [comment]
Hey @adrien3d, the `ErrorKind` stored in `error.kind` is an enum that can be matched on to determine the type of error returned. One of the variants is [`Write`](https://docs.rs/mongodb/latest/mongodb/error/enum.ErrorKind.html#variant.Write), which stores a `WriteFailure` containing a code. You could do something like this in the example you provided to extract the code:

```
let collection = client.database(DB_NAME).collection(users::REPOSITORY_NAME);
match collection.insert_one(user, None).await {
    Ok(_) => Ok(self),
    Err(error) => {
        match *error.kind {
            ErrorKind::Write(write_error) => {
                let code = write_error.code();
            }
        }
    }
}
```

Please let me know if you have any further questions!

**Comment by adrien3d** [comment]
Thank you, I think I am closer, but I can't make a `write_error.code()`, since, at least for `2.7.0`, method code is private: `pub(crate) fn code(&self) -> i32 {`

**Comment by isabelatkinson** [comment]
Ah apologies, I forgot that was not a public method. Thank you for including an updated code example!
