### ISSUE TITLE
Add `Server` module

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [mongodb/mongo-rust-driver#990]
In production my application uses Atlas, but to run integration tests locally I want to spawn a server for each test to ensure the environment is as clean as possible.

Doing this currently is quite a pain. It would be extremely helpful if there where a API to run the server binary.

It would be great if you could provide an example of how to do this testing with the current offerings of mongodb.

**Comment by abr-egn** [comment]
I'm afraid this is out of scope for the driver.

I'd recommend using mlaunch from the [mtools](https://github.com/rueckstiess/mtools) suite for local test environments - it's what I use for development and makes spinning up various sorts of deployments quite easy.  It should be straightforward to wrap that for the integration testing you describe.
